// AI-vs-AI seed round runner. Admin-only.
//
// One call = one simulated debate round. The runner UI loops this N times
// and shows progress per round. We deliberately do NOT batch in-function
// because Netlify caps execution at 26s and each round needs three
// sequential Claude calls (~12-15s total). Looping client-side keeps each
// invocation under the limit and makes failures isolated + retryable.
//
// Per-round flow:
//   1. Pick motion + format + two handles (one Gov, one Opp).
//   2. Claude generates Gov speech (200-280 words, sounds like a real speech).
//   3. Claude generates Opp speech engaging Gov directly.
//   4. Claude (as a judge) returns JSON: winner + RFD + speaker points.
//   5. Two leaderboard_entries docs written (one per side), tagged
//      simulated:true and uid prefixed 'ai-runner-' so they're identifiable.
//
// POST /api/seed-round
// body: { motion?, format?, dryRun? }
// resp: { ok, motion, formatName, gov, opp, judge, durationMs, written }
//
// Auth: admin only (ADMIN_UID env var OR user_profiles.{uid}.isAdmin === true).

import { verifyIdToken, extractBearerToken } from './lib/auth.mjs';
import { getDb, FieldValue } from './lib/firestore.mjs';
import { corsResponse, jsonResponse, errorResponse } from './lib/response.mjs';

const ADMIN_UID = process.env.ADMIN_UID || 'REPLACE_WITH_YOUR_FIREBASE_UID';
const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY;

// Haiku is the right tradeoff for batched runs: ~3-5s/call, $0.005/round
// total at typical token sizes. Sonnet would land cleaner cases but you
// pay 8x for marginally-better seeds nobody will read in detail.
const CLAUDE_MODEL = 'claude-haiku-4-5-20251001';

// Format bank — same weighting as community-seed.js so the runner-produced
// entries blend into the existing distribution. Keep slugs aligned with
// debate-it.html FORMATS so other parts of the pipeline (e.g. the Cases
// tab format filter) recognize them.
const FORMATS = [
  { slug:'asian',   name:'Asian Parli',     w:24, sideLabels:{ gov:'Government', opp:'Opposition' } },
  { slug:'bp',      name:'British Parli',   w:18, sideLabels:{ gov:'Opening Government', opp:'Opening Opposition' } },
  { slug:'apda',    name:'APDA',            w:11, sideLabels:{ gov:'Government', opp:'Opposition' } },
  { slug:'worlds',  name:'Worlds',          w:10, sideLabels:{ gov:'Opening Government', opp:'Opening Opposition' } },
  { slug:'pf',      name:'Public Forum',    w:10, sideLabels:{ gov:'Pro', opp:'Con' } },
  { slug:'ld',      name:'Lincoln-Douglas', w: 8, sideLabels:{ gov:'Affirmative', opp:'Negative' } },
];
const FORMAT_TOTAL_W = FORMATS.reduce((s,f)=>s+f.w,0);

// Motion bank — mix of timely + evergreen. Skewed slightly toward
// India-relevant + cross-format motions so the runner's output reinforces
// the existing seed personas' subject area without being too narrow.
const MOTIONS = [
  'THBT social media platforms should be legally liable for user-generated misinformation.',
  'THW prioritize economic growth over environmental regulation in developing economies.',
  'THBT artificial intelligence will do more harm than good in the next decade.',
  'THW abolish standardized testing as a factor in college admissions.',
  'THW grant nation-states full sovereignty over data generated by their citizens.',
  'On balance, NATO expansion since 1991 has been beneficial.',
  'THBT the 2024 Indian education reforms have done more good than harm.',
  'THW require platforms over 1M MAU to label AI-generated content.',
  'THBT free trade agreements have failed working-class voters in OECD economies.',
  'THW abolish the inheritance tax exemption for primary residences.',
  'THBT international students should be protected from political deportation.',
  'THW require all university research to be open-access within 12 months of publication.',
  'On balance, the global rise of populism has been a net negative for democracy.',
  'THW make voting compulsory for citizens over 18.',
  'THBT the EU should grant Ukraine accelerated accession membership.',
  'THW ban political parties from accepting corporate donations.',
  'THBT mandatory military service strengthens civic identity in fractured democracies.',
  'THW abolish the WTO dispute settlement mechanism.',
  'THBT cryptocurrencies should be treated as securities, not currencies.',
  'THW make university degrees subsidized only for fields with documented labor shortages.',
];

// Handle pool — same source as community-seed.js so the runner outputs
// look like organic sign-ups, not a separate bot fleet.
const HANDLES = [
  'parli_pilgrim','bp_overhang','pfdrops','kshell','theory_pls',
  'flow_rat','flowingok','tab_judge_no','1ar_collapse','2nr_god',
  'mgextension','whip_only','topicality_dad','condo_good','extend_pls',
  'octas_or_bust','wsdcbound','prelim_quad','linkturn','frontlinekid',
  'spreader','mango42','klondike','merlot','slowburn','aux_8',
  'tundra','hibachi','aarav','priya','meera','tarun','diya','connor',
  'niharika','sara','pranav','rohan','akhil','olivia','sebastian','vihaan',
  'cite_or_die','delhi_circuit','criterionkid','tabover_truth','closingoo',
  'oo_bench','crystallize','nightshift_',
];

function pick(arr, exclude){
  let pool = arr;
  if (exclude && exclude.length){
    pool = arr.filter(x => !exclude.includes(x));
  }
  return pool[Math.floor(Math.random() * pool.length)];
}
function pickWeightedFormat(){
  let n = Math.random() * FORMAT_TOTAL_W;
  for (const f of FORMATS){ if ((n -= f.w) <= 0) return f; }
  return FORMATS[0];
}

// Single-shot Claude call. Direct to Anthropic — bypasses the streaming
// claude.mjs proxy because we want batch JSON, not SSE.
async function callClaude(systemPrompt, userMessage, maxTokens){
  const r = await fetch('https://api.anthropic.com/v1/messages', {
    method:'POST',
    headers:{
      'Content-Type':'application/json',
      'x-api-key':ANTHROPIC_API_KEY,
      'anthropic-version':'2023-06-01',
    },
    body: JSON.stringify({
      model: CLAUDE_MODEL,
      max_tokens: maxTokens,
      system: systemPrompt,
      messages: [{ role:'user', content: userMessage }],
    }),
  });
  if (!r.ok){
    const txt = await r.text().catch(()=> '');
    throw new Error('Claude HTTP ' + r.status + ': ' + txt.slice(0, 200));
  }
  const j = await r.json();
  return (j.content && j.content[0] && j.content[0].text) || '';
}

// Strip code fences / leading commentary so the JSON parser can take it.
// Claude tends to wrap JSON in ```json ... ``` blocks even when told not to.
function extractJson(text){
  const m = text.match(/\{[\s\S]+\}/);
  if (!m) throw new Error('No JSON object in judge output');
  return JSON.parse(m[0]);
}

async function runOneRound(opts){
  const t0 = Date.now();
  const motion = opts.motion || pick(MOTIONS);
  const format = opts.format
    ? (FORMATS.find(f => f.slug === opts.format) || pickWeightedFormat())
    : pickWeightedFormat();
  const govHandle = pick(HANDLES);
  const oppHandle = pick(HANDLES, [govHandle]);

  // Gov speech first — no awareness of opp because it's the opening speech.
  const govSpeech = await callClaude(
    'You are ' + govHandle + ', a varsity debater on a competitive ' + format.name + ' circuit. ' +
    'You are arguing the ' + format.sideLabels.gov + ' side. Motion: "' + motion + '". ' +
    'Deliver a tight 220-280 word opening speech: define/characterize, present 2 arguments with warrants ' +
    'and impacts, brief crystallization. Read as a real speech (no headings, no bullets). ' +
    'No em-dashes; periods, commas, semicolons only.',
    'Speak now.',
    900
  );

  // Opp engages Gov directly.
  const oppSpeech = await callClaude(
    'You are ' + oppHandle + ', a varsity debater on the same ' + format.name + ' circuit. ' +
    'You are arguing the ' + format.sideLabels.opp + ' side. Motion: "' + motion + '". ' +
    'Gov (' + govHandle + ') just delivered:\n"""\n' + govSpeech + '\n"""\n' +
    'Deliver a 220-280 word reply: engage Gov\'s case directly, present 2 counter-arguments ' +
    'with warrants and impacts, weigh briefly. Read as a real speech. No em-dashes.',
    'Speak now.',
    900
  );

  // Judge as JSON. Be explicit about output shape.
  const judgeRaw = await callClaude(
    'You are an experienced ' + format.name + ' judge. Two debaters on motion "' + motion + '":\n\n' +
    'Gov (' + govHandle + '):\n"""\n' + govSpeech + '\n"""\n\n' +
    'Opp (' + oppHandle + '):\n"""\n' + oppSpeech + '\n"""\n\n' +
    'Return ONLY a JSON object, no commentary, no code fence:\n' +
    '{\n' +
    '  "winner": "gov" or "opp",\n' +
    '  "rfd": "80-120 word reasoning, plain prose, no headings",\n' +
    '  "govSpeakerPoints": number between 25.0 and 29.9 (one decimal),\n' +
    '  "oppSpeakerPoints": number between 25.0 and 29.9 (one decimal)\n' +
    '}',
    'Decide.',
    500
  );
  const judge = extractJson(judgeRaw);

  // Sanity-clamp scores so a misbehaving judge can't push outliers onto
  // the public board.
  const clamp = (n) => Math.max(25.0, Math.min(29.9, Number(n) || 26.0));
  const govScore = Math.round(clamp(judge.govSpeakerPoints) * 10) / 10;
  const oppScore = Math.round(clamp(judge.oppSpeakerPoints) * 10) / 10;
  const winner = (judge.winner === 'opp') ? 'opp' : 'gov';

  const result = {
    ok: true,
    motion, format: format.slug, formatName: format.name,
    gov: { handle: govHandle, score: govScore, won: winner === 'gov' },
    opp: { handle: oppHandle, score: oppScore, won: winner === 'opp' },
    judge: { winner, rfd: String(judge.rfd || '').slice(0, 600) },
    durationMs: Date.now() - t0,
    written: false,
  };

  if (opts.dryRun) return result;

  const db = getDb();
  const roundId = 'sim_' + Date.now() + '_' + Math.random().toString(36).slice(2, 8);
  const now = FieldValue.serverTimestamp();

  // Two leaderboard entries per round — one per side. Same shape as the
  // entries debate-it.html writes for live AI rounds, plus simulated:true
  // so admin filters can identify them later.
  const baseEntry = {
    motion,
    format: format.slug,
    formatName: format.name,
    completedAt: now,
    roundId,
    kind: 'ai',
    simulated: true,
    runner: 'seed-round',
  };
  const govEntry = {
    ...baseEntry,
    uid: 'ai-runner-' + govHandle,
    displayName: govHandle,
    score: govScore,
    won: winner === 'gov',
    side: 'gov',
    sideLabel: format.sideLabels.gov,
  };
  const oppEntry = {
    ...baseEntry,
    uid: 'ai-runner-' + oppHandle,
    displayName: oppHandle,
    score: oppScore,
    won: winner === 'opp',
    side: 'opp',
    sideLabel: format.sideLabels.opp,
  };

  await Promise.all([
    db.collection('leaderboard_entries').doc(govEntry.uid + '_' + roundId).set(govEntry),
    db.collection('leaderboard_entries').doc(oppEntry.uid + '_' + roundId).set(oppEntry),
  ]);

  result.written = true;
  result.roundId = roundId;
  return result;
}

export default async (request) => {
  if (request.method === 'OPTIONS') return corsResponse(request);
  if (request.method !== 'POST') return errorResponse('Method not allowed', 405, request);

  if (!ANTHROPIC_API_KEY){
    return errorResponse('ANTHROPIC_API_KEY is not configured.', 500, request);
  }

  const token = extractBearerToken(request);
  if (!token) return errorResponse('Authorization required', 401, request);

  let decoded;
  try { decoded = await verifyIdToken(token); }
  catch (err){
    console.error('seed-round auth error:', err.message);
    return errorResponse('Authentication failed. Please sign in again.', 401, request);
  }

  const uid = decoded.sub;
  const db = getDb();

  // Same admin gate as admin-backfill-leaderboard.mjs.
  let isAdmin = uid === ADMIN_UID;
  if (!isAdmin){
    try {
      const profileDoc = await db.collection('user_profiles').doc(uid).get();
      if (profileDoc.exists && profileDoc.data().isAdmin === true) isAdmin = true;
    } catch (err){
      console.error('seed-round profile check error:', err.message);
    }
  }
  if (!isAdmin) return errorResponse('Forbidden: admin access required', 403, request);

  let body = {};
  try { body = await request.json(); } catch {}

  try {
    const result = await runOneRound({
      motion: body.motion ? String(body.motion).slice(0, 400) : undefined,
      format: body.format ? String(body.format).slice(0, 20) : undefined,
      dryRun: !!body.dryRun,
    });
    return jsonResponse(result, 200, request);
  } catch (err){
    console.error('seed-round failed:', err.message);
    return jsonResponse({
      ok: false,
      error: err.message || 'Unknown error',
    }, 500, request);
  }
};

export const config = { path: '/api/seed-round' };
