// draft-motions.mjs — the slate pool for the pre-round motion draft.
//
// GENERATED FILE. Do not hand-edit. Source of truth is the canonical motion
// pools in app/practice.html; regenerate with:
//
//   node scripts/gen-draft-motions.mjs
//
// Every pool must hold at least SLATE_SIZE + 1 motions or a slate cannot be
// drawn without repeats. scripts/test-motion-draft.mjs asserts that in the
// pre-commit hook, because a short pool surfaces as a duplicated card in
// front of two real people mid-draft rather than as an error anyone sees.

export const DRAFT_MOTIONS = {

  quick: [
    'AI will lead to socialism.',
    'The AI boom is a bubble.',
    'AI will destroy more good jobs than it creates.',
    'AI will end the era of entry-level office work.',
    'AI will make college degrees less valuable.',
    'AI companies will become more powerful than governments.',
    'Open-source AI is more dangerous than corporate-controlled AI.',
    'AI companies should pay people whose work trained their models.',
    'AI-generated work should not receive copyright protection.',
    'Data centers should have to build their own power plants.',
    'Schools should treat AI like calculators, not cheating.',
    'AI companions will make people lonelier.',
    'Synthetic media will make video useless as evidence.',
    'The public should own AI systems trained mainly on public data.',
    'Companies should be responsible for every deal their AI agents make.',
    'AI will make experts more valuable, not less.',
    'AI will make a 32-hour workweek necessary.',
    'Democracies cannot control AI without losing the global race.',
    'Billionaires are a policy failure.',
    'Inheritance matters more than hard work in deciding who becomes rich.',
    'Universal basic income would weaken workers.',
    'Governments should guarantee a job to anyone who wants one.',
    'Wealth taxes are the only realistic way to prevent oligarchy.',
    'Private equity is making ordinary life worse.',
    'Economic growth matters more than economic equality.',
    'The next financial crisis will begin outside the banking system.',
    'Cash is essential to freedom.',
    'The gig economy gives workers more freedom than it takes away.',
    'Companies should be required to share productivity gains with workers.',
    'The minimum wage should rise automatically with local housing costs.',
    'Homeownership should stop being the main way families build wealth.',
    'Corporations should not be allowed to own single-family homes.',
    'Housing should be built even when current homeowners oppose it.',
    'Remote work will hollow out major cities.',
    'College has become a luxury signal rather than an education.',
    'Employers should stop requiring degrees for most professional jobs.',
    'Free speech cannot survive algorithmic feeds.',
    'Social media has made democracy less governable.',
    'Anonymous speech does more harm than good online.',
    'Every social media account should be tied to a real identity.',
    'Political ads made with AI should be banned.',
    'Recommendation algorithms should be public.',
    'News organizations should stop pretending to be neutral.',
    'Prediction markets will replace opinion polls.',
    'Citizens chosen by lottery would govern better than elected politicians.',
    'Voting should be mandatory.',
    'The voting age should be lowered to 16.',
    'The richest people have too much freedom to shape public opinion.',
    'Governments should be allowed to ban foreign-owned social platforms.',
    'Courts should be allowed to remove politicians who repeatedly lie.',
    'Deepfakes will strengthen trusted institutions rather than destroy them.',
    'The internet has ended the possibility of a shared reality.',
    'Democracies need secrecy to survive.',
    'Political parties make democracy worse.',
    'Protectionism will define the next global economy.',
    'Globalization made national democracy weaker.',
    'The U.S.-China rivalry matters more than ideology.',
    'Small countries should stay neutral between the U.S. and China.',
    'Sanctions hurt ordinary people more than the governments they target.',
    'The dollar will lose its global dominance within a generation.',
    'The next superpower will be a company, not a country.',
    'The Arctic will become the world\'s most important geopolitical region.',
    'National security matters more than free trade.',
    'Europe will decline unless it deregulates.',
    'A world of regional blocs will be safer than a globalized world.',
    'Nuclear weapons have prevented more wars than they have caused.',
    'Space exploration is becoming a new form of imperialism.',
    'Climate migration will make national borders stronger.',
    'Countries should trade only with governments that respect democracy.',
    'Military alliances make their members less safe.',
    'Global institutions have made powerful countries less accountable.',
    'Food security matters more than free agricultural trade.',
    'Nuclear power is the only realistic path to abundant clean energy.',
    'Data centers should be first to lose power during shortages.',
    'Electric cars distract from better public transit.',
    'Geoengineering is inevitable.',
    'Economic growth and climate stability are compatible.',
    'Energy abundance matters more than energy efficiency.',
    'Water should never be privately owned.',
    'The green transition will increase nationalism.',
    'Fossil fuel companies should pay for climate adaptation.',
    'Climate policy will fail unless it makes energy cheaper.',
    'Fusion power will arrive too late to matter.',
    'Rich countries should pay poorer countries for the costs of climate change.',
    'Governments should subsidize domestic manufacturing even when it raises prices.',
    'Air conditioning should be treated as essential infrastructure.',
    'Cities should charge drivers to enter downtown.',
    'The future belongs to cities, not suburbs.',
    'Rich countries should build clean industry at home instead of buying carbon offsets.',
    'People should pay more for goods with large carbon footprints.',
    'Smartphones should be illegal for people under 16.',
    'The internet has made culture less creative.',
    'Authenticity will become a luxury good.',
    'Loneliness is a political problem, not a private one.',
    'Dating apps have made relationships worse.',
    'People should have a legal right to disappear from the internet.',
    'Convenience has made people less capable.',
    'Fame is more harmful than wealth.',
    'Every teenager should work for a year before college.',
    'Professional sports should receive no public money.',
    'Parents should be allowed to keep their children completely offline.',
    'Adulthood should begin at 21, not 18.',
    'Human enhancement will create a permanent class system.',
    'The right to privacy is already dead.',
    'Streaming has made movies and music worse.',
    'Cities should stay open all night.',
    'Public schools should ban smartphones for the entire day.',
    'Universities should stay neutral on political questions.',
    'People will trust AI personalities more than public institutions.',
    'The decline of religion has made politics more extreme.',
    'National service would make divided societies stronger.',
    'Meritocracy is mostly a myth.',
    'Work gives life more meaning than leisure.',
    'The internet should forget everything after ten years.',
    'Celebrity activism does more harm than good.',
    'Sports unite divided societies better than politics can.',
    'The world would be better without targeted advertising.',
    'Democratic socialists should run America next.',
    'The next American realignment will be economic, not cultural.',
    'Class politics will replace identity politics in the West.',
    'Socialism is popular with young people because capitalism stopped delivering for them.',
    'Moderates lose the elections that radicals win.',
    'Mayors will matter more than presidents in the next decade.',
    'Public ownership works better than regulation.',
    'Democracies will nationalize their most important industries within a generation.',
    'Deregulation would do more for living standards than redistribution.',
    'Unions will matter more in the AI economy than they did in the industrial one.',
    'Labor will never recover the power it held in the twentieth century.',
    'The welfare state cannot survive an aging population.',
    'Rich countries cannot stay rich without high immigration.',
    'Free markets need a strong state to survive.',
    'Young people will stay more radical than their parents for life.',
    'Elections have stopped deciding economic policy.',
  ],

  apda: [
    'This house would ban billionaires.',
    'This house would abolish the electoral college.',
    'This house would make voting compulsory.',
    'This house believes the right to privacy is obsolete.',
    'This house would abolish the Senate.',
    'This house believes benevolent dictatorship is preferable to dysfunctional democracy.',
    'This house would grant constitutional rights to future generations.',
    'This house would allow citizens to sell their vote.',
    'This house believes free will is an illusion.',
    'This house believes moral progress is real.',
    'This house believes the ends justify the means.',
    'This house believes it is immoral to have children in the current era.',
    'This house would choose to live in a simulation that maximizes happiness.',
    'This house regrets the cultural dominance of English as a global language.',
    'This house prefers a world where humans cannot lie.',
    'This house believes AI development should be paused.',
    'This house would grant legal personhood to advanced AI systems.',
    'This house would replace juries with AI judges.',
    'This house regrets the invention of the smartphone.',
    'This house believes open-source AI is a net negative for humanity.',
    'This house would abolish legacy admissions.',
    'This house would ban private education.',
    'This house would eliminate standardized testing.',
    'This house believes universities should prioritize vocational training over liberal arts.',
    'This house would abolish prisons.',
    'This house would decriminalize sex work.',
    'This house would require police officers to hold professional licenses.',
    'This house would lower the voting age to 16.',
    'This house would mandate organ donation upon death.',
    'This house believes whistleblowers should receive absolute legal immunity.',
    'This house supports universal basic income.',
    'This house would abolish intellectual property for medicines.',
    'This house would ban unpaid internships.',
    'This house would impose a global carbon tax.',
    'This house would replace income tax with a wealth tax.',
    'This house would dissolve NATO.',
    'This house would create a world government.',
    'This house believes economic sanctions do more harm than good.',
    'This house believes animal advocacy should target changing people\'s preferences for meat, rather than pushing businesses to adopt close meat substitutes.',
    'After a heartbreak, this house opposes the narrative that one was only in love with "the idea" of their ex.',
    'Assuming shareholders are compensated, this house would require a majority of companies\' equity to be owned by sub-management employees.',
    'This house, as a left-wing party in Southeast Asia, would aggressively advocate for land redistribution.',
    'When running against populists, this house believes it is in the interests of establishment parties to avoid explicit appeals to identity.',
    'This house believes indigenous advocacy in Canada should prioritize obtaining government support rather than legal recognition of indigenous law.',
    'This house prefers a world where the majority of higher education is privately owned to one where it is publicly owned.',
    'This house supports search engines offering an unpersonalized results option by default.',
    'This house believes AI technologies will be on net beneficial for animal welfare.',
    'This house regrets the widespread use of bold and graphic imagery in feminist art.',
    'As a young person recently out of a long-term relationship, this house prefers avoiding romantic encounters rather than seeking many.',
    'This house supports a presidential coup by the military in Venezuela.',
    'This house would require major technology firms to sell off their artificial intelligence divisions.',
    'This house opposes narratives that children take after their parents.',
    'This house supports militaries\' current efforts to significantly increase their usage of artificial intelligence.',
    'This house believes it is in the interests of religious leaders to forbid the use of artificial intelligence for any religious purposes.',
    'This house believes the United States should legalize cocaine.',
    'This house supports the rise of students taking gap years before and during their post-secondary education.',
    'In countries with ruling far-right governments, this house believes queer movements should encourage their members to conceal rather than openly express their identities.',
    'This house believes Batman should kill the Joker.',
    'This house believes the Jedi were the true villains of Star Wars.',
    'This house would require superheroes to operate under government license.',
    'This house regrets the invention of agriculture.',
    'This house, offered a pill that stops aging, would take it.',
    'This house would require a license to become a parent.',
    'This house would replace Congress with citizens chosen by lottery.',
    'This house would broadcast humanity\'s location to alien civilizations.',
    'This house would make every salary public.',
    'This house believes soulmates are a harmful myth.',
    'This house would bring back dueling to settle defamation lawsuits.',
    'This house would legalize insider trading.',
    'This house believes the American Revolution was a mistake.',
    'This house would let citizens sell their citizenship to the highest bidder.',
    'This house believes multi-club ownership does more harm than good to soccer.',
    'This house would replace take-home essays with oral examinations.',
    'This house believes universities should stay institutionally neutral on contested political questions.',
    'This house, as the NCAA, would treat college athletes as employees.',
    'This house regrets the rise of prediction markets.',
    'This house would ban private equity firms from buying single-family homes.',
    'This house regrets the influencer economy.',
    'This house would replace juries with professional judges.',
    'This house believes the four-day work week should become the standard.',
  ],

  bp: [
    'This House would abolish the filibuster.',
    'This House would pack the Supreme Court.',
    'This House would condition US foreign aid on the recipient holding free elections.',
    'This House would substantially reduce US troop presence in the Middle East.',
    'This House would establish a federal jobs guarantee.',
    'This House would mandate corporate climate disclosure.',
    'This House would impose a global minimum corporate tax of 25%.',
    'This House would prosecute fossil-fuel executives for ecocide.',
    'This House would ban the export of dual-use surveillance technology.',
    'This House would reduce the powers of UN Security Council permanent members.',
    'This House, as the EU, would mandate algorithmic transparency for major social media platforms.',
    'This House, as the Global South, would default on sovereign debt held by Western creditors.',
    'This House, as the African Union, would create a continental currency.',
    'This House, as the Democratic Party, would abandon means-testing in social policy.',
    'This House, as the Republican Party, would abandon Trumpism after 2028.',
    'This House, as a centre-left government, would adopt unconditional cash transfers.',
    'This House would create a binding international treaty on AI weapons.',
    'This House would establish an international court for AI harms.',
    'This House would require AI-generated content to be watermarked.',
    'This House would ban deepfake content of real people without consent.',
    'This House supports a UN-mandated military intervention in Sudan.',
    'This House would suspend Israel from the UN General Assembly.',
    'This House regrets the rise of populism in liberal democracies.',
    'This House regrets the rise of identity politics as a frame for left-wing political organizing.',
    'This House would replace the IMF with a multipolar lending body.',
    'This House would abolish parole boards.',
    'This House would ban political dynasties.',
    'This House would conscript billionaires to fund climate adaptation.',
    'This House would ban political advertising on social media.',
    'This House would require labor representation on US corporate boards.',
    'This House would replace one chamber of the legislature with a citizens\' assembly chosen by lottery.',
    'This House would nationalise frontier AI labs.',
    'This House would criminalise lying by elected officials.',
    'This House would legalise regulated markets in citizenship.',
    'This House would allow prediction markets on all political outcomes, including elections.',
    'This House believes the United States would be better off as several smaller countries.',
    'This House would seize frozen Russian state assets to fund the reconstruction of Ukraine.',
    'This House supports the nuclear renaissance.',
    'This House would break up Google.',
    'This House would require AI developers to license the copyrighted work used to train their models.',
    'This House would introduce a robot tax on labor-displacing automation.',
    'This House would bar authoritarian states from hosting international sporting events.',
    'This House supports central bank digital currencies.',
    'This House, as the European Union, would pursue strategic autonomy from the United States.',
  ],

  worlds: [
    'This House would ban homework for K-12 students.',
    'This House would make voting compulsory.',
    'This House supports the existence of separatist movements in democratic states.',
    'This House would ban single-use plastics globally.',
    'This House would lower the voting age to 16.',
    'This House regrets the rise of nationalism.',
    'This House would require ranked-choice voting in national elections.',
    'This House would ban factory farming.',
    'This House supports open borders.',
    'This House would create a world government.',
    'This House would grant legal standing to ecosystems.',
    'This House would ban performance-enhancing drugs in professional sports.',
    'This House would mandate civic education in every secondary school curriculum.',
    'This House would replace standardized testing with portfolio-based admissions.',
    'This House would abolish daylight saving time.',
    'This House would require all elected officials to publish their tax returns.',
    'This House would tax church property at the same rate as commercial property.',
    'This House would ban advertising to children under 16.',
    'This House would require ID verification to use social media.',
    'This House would replace the SAT with a national civic-knowledge exam.',
    'This House would mandate parental leave of at least 6 months.',
    'This House would replace prison with mandatory restorative justice for non-violent offenses.',
    'This House would require corporations above $1B revenue to publish their algorithms.',
    'This House would ban genetic engineering of human embryos.',
    'This House supports the use of nuclear power to fight climate change.',
    'This House would ban zoos.',
    'This House would pay students to attend school.',
    'This House would bring extinct species back to life.',
    'This House would send messages into space announcing humanity\'s location.',
    'This House would give children a vote, cast by their parents.',
    'This House would ban boxing and tackle football for under-18s.',
    'This House would ban smartphones in schools.',
    'This House believes social media does more harm than good for teenagers.',
    'This House would make climate education a compulsory school subject.',
    'This House would grant permanent residents the right to vote in local elections.',
    'This House supports congestion charges in major cities.',
    'This House would criminalize ecocide.',
  ],

  asian: [
    'This House, as ASEAN, would adopt a binding South China Sea code of conduct.',
    'This House, as the Philippines, would accept Chinese infrastructure investment in disputed waters.',
    'This House, as India, would scrap caste-based affirmative action.',
    'This House would require Indian states to adopt a uniform civil code.',
    'This House regrets the rise of Hindu nationalism in India.',
    'This House, as Indonesia, would relocate its capital to Nusantara on a faster timeline.',
    'This House supports a UN Security Council permanent seat for India.',
    'This House, as the Indian government, would ban arranged marriages where one party is under 21.',
    'This House supports cash transfers over food subsidies in low-income Asian economies.',
    'This House would tax remittances to fund domestic employment.',
    'This House supports a coordinated South Asian renewables grid.',
    'This House regrets the IMF\'s role in the 1997 Asian Financial Crisis.',
    'This House would adopt Singapore-style meritocratic governance across developing Asian economies.',
    'This House would prioritize gender quotas over caste quotas in Indian higher education.',
    'This House, as the EU, would treat the Belt and Road Initiative as a strategic threat.',
    'This House regrets the rise of China as the regional hegemon of East Asia.',
    'This House, as Sri Lanka, would default on Chinese sovereign debt.',
    'This House regrets the spread of cram-school culture in East Asia.',
    'This House would scrap the gaokao / JEE / KSAT in favor of holistic university admissions.',
    'This House, as the Indian government, would treat coaching institutes as a regulated education sector.',
    'This House would issue climate visas to Pacific Island residents.',
    'This House would impose a regional carbon border tax across APEC economies.',
    'This House, as Bangladesh, would prioritize relocation of climate-displaced persons over coastal adaptation.',
    'This House would condition trade with Myanmar on the release of political prisoners.',
    'This House supports a unified Korean peninsula under a federal arrangement.',
    'This House would grant the Ganges the legal rights of a person.',
    'This House regrets the K-pop idol-trainee system.',
    'This House would pay couples in aging East Asian economies to have children.',
    'This House, as the Indian government, would cap wedding spending.',
    'This House supports simultaneous national and state elections in India.',
    'This House, as South Korea, would develop an independent nuclear deterrent.',
    'This House, as Indonesia, would keep its raw nickel export ban permanently.',
    'This House believes the Gulf migration corridor does South Asia more good than harm.',
    'This House supports a BRICS common currency.',
    'This House, as ASEAN, would fast-track Timor-Leste\'s full membership.',
  ],

  ld: [
    'Government benefits should be automatic instead of something you apply for.',
    'Breaking the law in protest can be justified in a democracy.',
    'Resolved: Individual rights ought to be valued above the collective good.',
    'Resolved: A just government ought to provide a universal basic income to its citizens.',
    'Resolved: It is morally permissible to break an unjust law.',
    'Resolved: Inaction in the face of injustice makes individuals morally culpable.',
    'Resolved: The protection of domestic civil liberties ought to be valued above the prevention of terrorism.',
    'Resolved: A just government ought to prioritize liberty over equality.',
    'Resolved: Reparations from majority populations to historically oppressed groups are morally justified.',
    'Resolved: Restorative justice is preferable to retributive justice.',
    'Resolved: A just society ought to recognize a right of secession.',
    'Resolved: Truth-telling ought to be valued above the prevention of harm.',
    'Resolved: It is morally permissible for victims to use deadly force as deliberate retaliation against repeated abuse.',
    'Resolved: In a democracy, voting ought to be a moral obligation.',
    'Resolved: A just government ought to prohibit the private ownership of firearms.',
  ],

  pf: [
    'Resolved: The United States federal government should substantially restrict the export of advanced semiconductor manufacturing equipment to the People\'s Republic of China.',
    'Resolved: The benefits of the BRICS expansion outweigh the harms.',
    'Resolved: The United States federal government should substantially increase its military presence in the Arctic.',
    'Resolved: The United States federal government should substantially increase humanitarian assistance to Sudan.',
    'Resolved: The United Nations should establish a binding international treaty governing the development of artificial intelligence.',
    'Resolved: On balance, the rise of generative artificial intelligence has been beneficial to the United States economy.',
    'Resolved: The United States federal government should prioritize reducing economic inequality over reducing the federal deficit.',
    'Resolved: The United States should ratify the Convention on the Rights of the Child.',
    'Resolved: The North Atlantic Treaty Organization should admit Ukraine as a member state.',
    'Resolved: The United States federal government should substantially increase its regulation of cryptocurrency.',
    'Resolved: The United States federal government should substantially increase its security cooperation with NATO in the cyber domain.',
    'Resolved: The benefits of NATO\'s expansion since 1991 outweigh the harms.',
    'Resolved: The United States should accede to the United Nations Convention on the Law of the Sea.',
    'Resolved: The People\'s Republic of China is a greater threat to U.S. interests than the Russian Federation.',
    'Resolved: The United States federal government should substantially increase its investment in artificial intelligence research and development.',
    'Resolved: The European Union should abolish the unanimity requirement for foreign-policy decisions.',
    'Resolved: On balance, the benefits of social media for adolescents outweigh the harms.',
    'Resolved: The United States should adopt a single-payer universal healthcare system.',
    'Resolved: The United Nations should grant the African Union a permanent seat on the Security Council.',
    'Resolved: The United States federal government should ban TikTok.',
    'Resolved: The United States federal government should substantially increase economic and military aid to Taiwan.',
    'Resolved: The benefits of corporate use of generative AI outweigh the harms.',
    'Resolved: The United States federal government should require an ID to access pornographic websites.',
    'Resolved: On balance, the benefits of nuclear power outweigh the harms.',
    'Resolved: The United States federal government should pay reparations to the descendants of enslaved persons.',
  ],

  policy: [
    'Resolved: The United States federal government should substantially increase its investment in domestic semiconductor manufacturing.',
    'Resolved: The United States federal government should substantially increase its diplomatic and economic engagement with the African Union.',
    'Resolved: The United States federal government should substantially reduce its military presence in one or more of the following: the Arabian Peninsula, the Korean Peninsula, the Republic of the Philippines.',
    'Resolved: The United States federal government should substantially increase fiscal redistribution toward persons living in poverty in the United States.',
    'Resolved: The United States federal government should establish a Carbon Border Adjustment Mechanism.',
    'Resolved: The United States federal government should substantially increase legal protections for LGBTQ persons in the United States.',
    'Resolved: The United States federal government should substantially increase its investment in K-12 STEM education.',
    'Resolved: The United States federal government should establish a federal jobs guarantee.',
    'Resolved: The United States federal government should substantially increase its public health infrastructure for pandemic preparedness.',
    'Resolved: The United States federal government should substantially increase the regulation of large-language-model artificial intelligence systems.',
  ],

  congress: [
    'A Resolution to Recognize Climate Change as a National Security Threat',
    'A Bill to Establish a Federal Right to Repair Electronic Devices',
    'A Resolution to Condemn the Development and Use of Lethal Autonomous Weapons Systems',
    'A Bill to Provide Universal Pre-Kindergarten Education to All American Children',
    'A Resolution Calling for the Abolition of the Electoral College',
    'A Bill to Mandate Algorithmic Transparency for Major Social Media Platforms',
    'A Resolution to Recognize Statehood for Washington, D.C.',
    'A Bill to Cancel All Federally Held Student Loan Debt',
    'A Resolution to Strengthen Sanctions Against the Russian Federation',
    'A Bill to Establish a Federal Wealth Tax on Net Worth Above Fifty Million Dollars',
    'A Bill to Implement a Carbon Tax with Per-Capita Dividends',
    'A Resolution to End the United States Embargo of Cuba',
    'A Bill to Require Public Disclosure of Congressional Stock Trades Within Twenty-Four Hours',
    'A Resolution to Withdraw the United States from the World Trade Organization',
  ],

  mun: [
    'UNSC: The Situation in Sudan',
    'WHO: Strengthening Global Pandemic Preparedness and Response',
    'UNGA-1 (DISEC): Regulation of Lethal Autonomous Weapons Systems',
    'UNHRC: Protecting the Rights of Climate-Displaced Persons',
    'ECOSOC: Closing the Global Digital Divide',
    'UNSC: The Question of Taiwan',
    'UNGA-3 (SOCHUM): Combating Disinformation in the Age of Generative AI',
    'UNESCO: Restitution of Cultural Property to Countries of Origin',
    'IAEA: The Iranian Nuclear Program',
    'UNEP: Financing Loss and Damage from Climate Change',
    'UNDP: Sovereign Debt Relief for the Global South',
    'UN Women: Expanding Women\'s Access to Public Office',
    'UNSC: Reform of the Permanent Membership and Veto',
    'UNGA-2 (ECOFIN): Reforming the International Tax Architecture',
    'UNHRC: Internet Shutdowns and the Right to Free Expression',
    'WHO: Equitable Access to mRNA Vaccine Technology',
  ],
};

// A format with no pool of its own draws from the plain-language Quick Clash
// pool. 'casual' is the live case: /debate-chat pairs ride the same queue
// collection and never opt into a draft, but the fallback keeps a future
// opt-in from ever drawing an empty slate.
export const DRAFT_FALLBACK_FORMAT = 'quick';

export function draftPoolFor(format) {
  const key = String(format || '').toLowerCase();
  const pool = DRAFT_MOTIONS[key];
  return (pool && pool.length) ? pool : DRAFT_MOTIONS[DRAFT_FALLBACK_FORMAT];
}
