// draft-motions.mjs — the slate pool for the pre-round motion draft.
//
// GENERATED FILE. Do not hand-edit. Source of truth is the canonical motion
// pools in app/practice.html; regenerate with:
//
//   node scripts/gen-draft-motions.mjs
//
// Every pool must hold at least SLATE_SIZE + 1 motions or a slate cannot be
// drawn without repeats. scripts/test-motion-draft.mjs asserts that in the
// pre-commit hook, because a short pool surfaces as a duplicated card in
// front of two real people mid-draft rather than as an error anyone sees.

export const DRAFT_MOTIONS = {

  quick: [
    'ICE should be allowed to arrest people at schools, courts, and hospitals.',
    'Members of Congress should be banned from trading stocks.',
    'The National Guard should be sent into U.S. cities to fight crime.',
    'The U.S. should ban TikTok unless it sells to an American owner.',
    'Billionaires should pay a yearly tax on wealth they have not sold.',
    'The U.S. should put tariffs on all imported goods.',
    'The Electoral College should be abolished.',
    'The voting age should be lowered to 16.',
    'The U.S. should recognize a Palestinian state.',
    'Public universities should be banned from running DEI programs.',
    'Assault-style rifles should be banned for civilians.',
    'Undocumented immigrants brought here as children should get citizenship.',
    'Social media should be banned for kids under 16.',
    'Tuition should be free at public universities.',
    'Student loan debt should be canceled.',
    'Gas-powered cars should be banned by 2035.',
    'Batman should kill the Joker.',
    'Parents should need a license to have kids.',
    'All salaries should be public.',
    'We should bring back extinct animals like the woolly mammoth.',
    'Politicians who lie should be jailed.',
    'We should colonize Mars before fixing Earth.',
    'Betting on elections should be legal.',
    'Politicians should be picked by lottery, like jury duty.',
  ],

  apda: [
    'This house would ban billionaires.',
    'This house would abolish the electoral college.',
    'This house would make voting compulsory.',
    'This house believes the right to privacy is obsolete.',
    'This house would abolish the Senate.',
    'This house believes benevolent dictatorship is preferable to dysfunctional democracy.',
    'This house would grant constitutional rights to future generations.',
    'This house would allow citizens to sell their vote.',
    'This house believes free will is an illusion.',
    'This house believes moral progress is real.',
    'This house believes the ends justify the means.',
    'This house believes it is immoral to have children in the current era.',
    'This house would choose to live in a simulation that maximizes happiness.',
    'This house regrets the cultural dominance of English as a global language.',
    'This house prefers a world where humans cannot lie.',
    'This house believes AI development should be paused.',
    'This house would grant legal personhood to advanced AI systems.',
    'This house would replace juries with AI judges.',
    'This house regrets the invention of the smartphone.',
    'This house believes open-source AI is a net negative for humanity.',
    'This house would abolish legacy admissions.',
    'This house would ban private education.',
    'This house would eliminate standardized testing.',
    'This house believes universities should prioritize vocational training over liberal arts.',
    'This house would abolish prisons.',
    'This house would decriminalize sex work.',
    'This house would require police officers to hold professional licenses.',
    'This house would lower the voting age to 16.',
    'This house would mandate organ donation upon death.',
    'This house believes whistleblowers should receive absolute legal immunity.',
    'This house supports universal basic income.',
    'This house would abolish intellectual property for medicines.',
    'This house would ban unpaid internships.',
    'This house would impose a global carbon tax.',
    'This house would replace income tax with a wealth tax.',
    'This house would dissolve NATO.',
    'This house would create a world government.',
    'This house believes economic sanctions do more harm than good.',
    'This house believes animal advocacy should target changing people\'s preferences for meat, rather than pushing businesses to adopt close meat substitutes.',
    'After a heartbreak, this house opposes the narrative that one was only in love with "the idea" of their ex.',
    'Assuming shareholders are compensated, this house would require a majority of companies\' equity to be owned by sub-management employees.',
    'This house, as a left-wing party in Southeast Asia, would aggressively advocate for land redistribution.',
    'When running against populists, this house believes it is in the interests of establishment parties to avoid explicit appeals to identity.',
    'This house believes indigenous advocacy in Canada should prioritize obtaining government support rather than legal recognition of indigenous law.',
    'This house prefers a world where the majority of higher education is privately owned to one where it is publicly owned.',
    'This house supports search engines offering an unpersonalized results option by default.',
    'This house believes AI technologies will be on net beneficial for animal welfare.',
    'This house regrets the widespread use of bold and graphic imagery in feminist art.',
    'As a young person recently out of a long-term relationship, this house prefers avoiding romantic encounters rather than seeking many.',
    'This house supports a presidential coup by the military in Venezuela.',
    'This house would require major technology firms to sell off their artificial intelligence divisions.',
    'This house opposes narratives that children take after their parents.',
    'This house supports militaries\' current efforts to significantly increase their usage of artificial intelligence.',
    'This house believes it is in the interests of religious leaders to forbid the use of artificial intelligence for any religious purposes.',
    'This house believes the United States should legalize cocaine.',
    'This house supports the rise of students taking gap years before and during their post-secondary education.',
    'In countries with ruling far-right governments, this house believes queer movements should encourage their members to conceal rather than openly express their identities.',
    'This house believes Batman should kill the Joker.',
    'This house believes the Jedi were the true villains of Star Wars.',
    'This house would require superheroes to operate under government license.',
    'This house regrets the invention of agriculture.',
    'This house, offered a pill that stops aging, would take it.',
    'This house would require a license to become a parent.',
    'This house would replace Congress with citizens chosen by lottery.',
    'This house would broadcast humanity\'s location to alien civilizations.',
    'This house would make every salary public.',
    'This house believes soulmates are a harmful myth.',
    'This house would bring back dueling to settle defamation lawsuits.',
    'This house would legalize insider trading.',
    'This house believes the American Revolution was a mistake.',
    'This house would let citizens sell their citizenship to the highest bidder.',
    'This house believes multi-club ownership does more harm than good to soccer.',
    'This house would replace take-home essays with oral examinations.',
    'This house believes universities should stay institutionally neutral on contested political questions.',
    'This house, as the NCAA, would treat college athletes as employees.',
    'This house regrets the rise of prediction markets.',
    'This house would ban private equity firms from buying single-family homes.',
    'This house regrets the influencer economy.',
    'This house would replace juries with professional judges.',
    'This house believes the four-day work week should become the standard.',
  ],

  bp: [
    'This House would abolish the filibuster.',
    'This House would pack the Supreme Court.',
    'This House would condition US foreign aid on the recipient holding free elections.',
    'This House would substantially reduce US troop presence in the Middle East.',
    'This House would establish a federal jobs guarantee.',
    'This House would mandate corporate climate disclosure.',
    'This House would impose a global minimum corporate tax of 25%.',
    'This House would prosecute fossil-fuel executives for ecocide.',
    'This House would ban the export of dual-use surveillance technology.',
    'This House would reduce the powers of UN Security Council permanent members.',
    'This House, as the EU, would mandate algorithmic transparency for major social media platforms.',
    'This House, as the Global South, would default on sovereign debt held by Western creditors.',
    'This House, as the African Union, would create a continental currency.',
    'This House, as the Democratic Party, would abandon means-testing in social policy.',
    'This House, as the Republican Party, would abandon Trumpism after 2028.',
    'This House, as a centre-left government, would adopt unconditional cash transfers.',
    'This House would create a binding international treaty on AI weapons.',
    'This House would establish an international court for AI harms.',
    'This House would require AI-generated content to be watermarked.',
    'This House would ban deepfake content of real people without consent.',
    'This House supports a UN-mandated military intervention in Sudan.',
    'This House would suspend Israel from the UN General Assembly.',
    'This House regrets the rise of populism in liberal democracies.',
    'This House regrets the rise of identity politics as a frame for left-wing political organizing.',
    'This House would replace the IMF with a multipolar lending body.',
    'This House would abolish parole boards.',
    'This House would ban political dynasties.',
    'This House would conscript billionaires to fund climate adaptation.',
    'This House would ban political advertising on social media.',
    'This House would require labor representation on US corporate boards.',
    'This House would replace one chamber of the legislature with a citizens\' assembly chosen by lottery.',
    'This House would nationalise frontier AI labs.',
    'This House would criminalise lying by elected officials.',
    'This House would legalise regulated markets in citizenship.',
    'This House would allow prediction markets on all political outcomes, including elections.',
    'This House believes the United States would be better off as several smaller countries.',
    'This House would seize frozen Russian state assets to fund the reconstruction of Ukraine.',
    'This House supports the nuclear renaissance.',
    'This House would break up Google.',
    'This House would require AI developers to license the copyrighted work used to train their models.',
    'This House would introduce a robot tax on labor-displacing automation.',
    'This House would bar authoritarian states from hosting international sporting events.',
    'This House supports central bank digital currencies.',
    'This House, as the European Union, would pursue strategic autonomy from the United States.',
  ],

  worlds: [
    'This House would ban homework for K-12 students.',
    'This House would make voting compulsory.',
    'This House supports the existence of separatist movements in democratic states.',
    'This House would ban single-use plastics globally.',
    'This House would lower the voting age to 16.',
    'This House regrets the rise of nationalism.',
    'This House would require ranked-choice voting in national elections.',
    'This House would ban factory farming.',
    'This House supports open borders.',
    'This House would create a world government.',
    'This House would grant legal standing to ecosystems.',
    'This House would ban performance-enhancing drugs in professional sports.',
    'This House would mandate civic education in every secondary school curriculum.',
    'This House would replace standardized testing with portfolio-based admissions.',
    'This House would abolish daylight saving time.',
    'This House would require all elected officials to publish their tax returns.',
    'This House would tax church property at the same rate as commercial property.',
    'This House would ban advertising to children under 16.',
    'This House would require ID verification to use social media.',
    'This House would replace the SAT with a national civic-knowledge exam.',
    'This House would mandate parental leave of at least 6 months.',
    'This House would replace prison with mandatory restorative justice for non-violent offenses.',
    'This House would require corporations above $1B revenue to publish their algorithms.',
    'This House would ban genetic engineering of human embryos.',
    'This House supports the use of nuclear power to fight climate change.',
    'This House would ban zoos.',
    'This House would pay students to attend school.',
    'This House would bring extinct species back to life.',
    'This House would send messages into space announcing humanity\'s location.',
    'This House would give children a vote, cast by their parents.',
    'This House would ban boxing and tackle football for under-18s.',
    'This House would ban smartphones in schools.',
    'This House believes social media does more harm than good for teenagers.',
    'This House would make climate education a compulsory school subject.',
    'This House would grant permanent residents the right to vote in local elections.',
    'This House supports congestion charges in major cities.',
    'This House would criminalize ecocide.',
  ],

  asian: [
    'This House, as ASEAN, would adopt a binding South China Sea code of conduct.',
    'This House, as the Philippines, would accept Chinese infrastructure investment in disputed waters.',
    'This House, as India, would scrap caste-based affirmative action.',
    'This House would require Indian states to adopt a uniform civil code.',
    'This House regrets the rise of Hindu nationalism in India.',
    'This House, as Indonesia, would relocate its capital to Nusantara on a faster timeline.',
    'This House supports a UN Security Council permanent seat for India.',
    'This House, as the Indian government, would ban arranged marriages where one party is under 21.',
    'This House supports cash transfers over food subsidies in low-income Asian economies.',
    'This House would tax remittances to fund domestic employment.',
    'This House supports a coordinated South Asian renewables grid.',
    'This House regrets the IMF\'s role in the 1997 Asian Financial Crisis.',
    'This House would adopt Singapore-style meritocratic governance across developing Asian economies.',
    'This House would prioritize gender quotas over caste quotas in Indian higher education.',
    'This House, as the EU, would treat the Belt and Road Initiative as a strategic threat.',
    'This House regrets the rise of China as the regional hegemon of East Asia.',
    'This House, as Sri Lanka, would default on Chinese sovereign debt.',
    'This House regrets the spread of cram-school culture in East Asia.',
    'This House would scrap the gaokao / JEE / KSAT in favor of holistic university admissions.',
    'This House, as the Indian government, would treat coaching institutes as a regulated education sector.',
    'This House would issue climate visas to Pacific Island residents.',
    'This House would impose a regional carbon border tax across APEC economies.',
    'This House, as Bangladesh, would prioritize relocation of climate-displaced persons over coastal adaptation.',
    'This House would condition trade with Myanmar on the release of political prisoners.',
    'This House supports a unified Korean peninsula under a federal arrangement.',
    'This House would grant the Ganges the legal rights of a person.',
    'This House regrets the K-pop idol-trainee system.',
    'This House would pay couples in aging East Asian economies to have children.',
    'This House, as the Indian government, would cap wedding spending.',
    'This House supports simultaneous national and state elections in India.',
    'This House, as South Korea, would develop an independent nuclear deterrent.',
    'This House, as Indonesia, would keep its raw nickel export ban permanently.',
    'This House believes the Gulf migration corridor does South Asia more good than harm.',
    'This House supports a BRICS common currency.',
    'This House, as ASEAN, would fast-track Timor-Leste\'s full membership.',
  ],

  ld: [
    'Resolved: A just government ought to make public services available by default rather than by application.',
    'Resolved: Civil disobedience in a democracy is morally justified.',
    'Resolved: Individual rights ought to be valued above the collective good.',
    'Resolved: A just government ought to provide a universal basic income to its citizens.',
    'Resolved: It is morally permissible to break an unjust law.',
    'Resolved: Inaction in the face of injustice makes individuals morally culpable.',
    'Resolved: The protection of domestic civil liberties ought to be valued above the prevention of terrorism.',
    'Resolved: A just government ought to prioritize liberty over equality.',
    'Resolved: Reparations from majority populations to historically oppressed groups are morally justified.',
    'Resolved: Restorative justice is preferable to retributive justice.',
    'Resolved: A just society ought to recognize a right of secession.',
    'Resolved: Truth-telling ought to be valued above the prevention of harm.',
    'Resolved: It is morally permissible for victims to use deadly force as deliberate retaliation against repeated abuse.',
    'Resolved: In a democracy, voting ought to be a moral obligation.',
    'Resolved: A just government ought to prohibit the private ownership of firearms.',
  ],

  pf: [
    'Resolved: The United States federal government should substantially restrict the export of advanced semiconductor manufacturing equipment to the People\'s Republic of China.',
    'Resolved: The benefits of the BRICS expansion outweigh the harms.',
    'Resolved: The United States federal government should substantially increase its military presence in the Arctic.',
    'Resolved: The United States federal government should substantially increase humanitarian assistance to Sudan.',
    'Resolved: The United Nations should establish a binding international treaty governing the development of artificial intelligence.',
    'Resolved: On balance, the rise of generative artificial intelligence has been beneficial to the United States economy.',
    'Resolved: The United States federal government should prioritize reducing economic inequality over reducing the federal deficit.',
    'Resolved: The United States should ratify the Convention on the Rights of the Child.',
    'Resolved: The North Atlantic Treaty Organization should admit Ukraine as a member state.',
    'Resolved: The United States federal government should substantially increase its regulation of cryptocurrency.',
    'Resolved: The United States federal government should substantially increase its security cooperation with NATO in the cyber domain.',
    'Resolved: The benefits of NATO\'s expansion since 1991 outweigh the harms.',
    'Resolved: The United States should accede to the United Nations Convention on the Law of the Sea.',
    'Resolved: The People\'s Republic of China is a greater threat to U.S. interests than the Russian Federation.',
    'Resolved: The United States federal government should substantially increase its investment in artificial intelligence research and development.',
    'Resolved: The European Union should abolish the unanimity requirement for foreign-policy decisions.',
    'Resolved: On balance, the benefits of social media for adolescents outweigh the harms.',
    'Resolved: The United States should adopt a single-payer universal healthcare system.',
    'Resolved: The United Nations should grant the African Union a permanent seat on the Security Council.',
    'Resolved: The United States federal government should ban TikTok.',
    'Resolved: The United States federal government should substantially increase economic and military aid to Taiwan.',
    'Resolved: The benefits of corporate use of generative AI outweigh the harms.',
    'Resolved: The United States federal government should require an ID to access pornographic websites.',
    'Resolved: On balance, the benefits of nuclear power outweigh the harms.',
    'Resolved: The United States federal government should pay reparations to the descendants of enslaved persons.',
  ],

  policy: [
    'Resolved: The United States federal government should substantially increase its investment in domestic semiconductor manufacturing.',
    'Resolved: The United States federal government should substantially increase its diplomatic and economic engagement with the African Union.',
    'Resolved: The United States federal government should substantially reduce its military presence in one or more of the following: the Arabian Peninsula, the Korean Peninsula, the Republic of the Philippines.',
    'Resolved: The United States federal government should substantially increase fiscal redistribution toward persons living in poverty in the United States.',
    'Resolved: The United States federal government should establish a Carbon Border Adjustment Mechanism.',
    'Resolved: The United States federal government should substantially increase legal protections for LGBTQ persons in the United States.',
    'Resolved: The United States federal government should substantially increase its investment in K-12 STEM education.',
    'Resolved: The United States federal government should establish a federal jobs guarantee.',
    'Resolved: The United States federal government should substantially increase its public health infrastructure for pandemic preparedness.',
    'Resolved: The United States federal government should substantially increase the regulation of large-language-model artificial intelligence systems.',
  ],

  congress: [
    'A Resolution to Recognize Climate Change as a National Security Threat',
    'A Bill to Establish a Federal Right to Repair Electronic Devices',
    'A Resolution to Condemn the Development and Use of Lethal Autonomous Weapons Systems',
    'A Bill to Provide Universal Pre-Kindergarten Education to All American Children',
    'A Resolution Calling for the Abolition of the Electoral College',
    'A Bill to Mandate Algorithmic Transparency for Major Social Media Platforms',
    'A Resolution to Recognize Statehood for Washington, D.C.',
    'A Bill to Cancel All Federally Held Student Loan Debt',
    'A Resolution to Strengthen Sanctions Against the Russian Federation',
    'A Bill to Establish a Federal Wealth Tax on Net Worth Above Fifty Million Dollars',
    'A Bill to Implement a Carbon Tax with Per-Capita Dividends',
    'A Resolution to End the United States Embargo of Cuba',
    'A Bill to Require Public Disclosure of Congressional Stock Trades Within Twenty-Four Hours',
    'A Resolution to Withdraw the United States from the World Trade Organization',
  ],

  mun: [
    'UNSC: The Situation in Sudan',
    'WHO: Strengthening Global Pandemic Preparedness and Response',
    'UNGA-1 (DISEC): Regulation of Lethal Autonomous Weapons Systems',
    'UNHRC: Protecting the Rights of Climate-Displaced Persons',
    'ECOSOC: Closing the Global Digital Divide',
    'UNSC: The Question of Taiwan',
    'UNGA-3 (SOCHUM): Combating Disinformation in the Age of Generative AI',
    'UNESCO: Restitution of Cultural Property to Countries of Origin',
    'IAEA: The Iranian Nuclear Program',
    'UNEP: Financing Loss and Damage from Climate Change',
    'UNDP: Sovereign Debt Relief for the Global South',
    'UN Women: Expanding Women\'s Access to Public Office',
    'UNSC: Reform of the Permanent Membership and Veto',
    'UNGA-2 (ECOFIN): Reforming the International Tax Architecture',
    'UNHRC: Internet Shutdowns and the Right to Free Expression',
    'WHO: Equitable Access to mRNA Vaccine Technology',
  ],
};

// A format with no pool of its own draws from the plain-language Quick Clash
// pool. 'casual' is the live case: /debate-chat pairs ride the same queue
// collection and never opt into a draft, but the fallback keeps a future
// opt-in from ever drawing an empty slate.
export const DRAFT_FALLBACK_FORMAT = 'quick';

export function draftPoolFor(format) {
  const key = String(format || '').toLowerCase();
  const pool = DRAFT_MOTIONS[key];
  return (pool && pool.length) ? pool : DRAFT_MOTIONS[DRAFT_FALLBACK_FORMAT];
}
