// Education bank — substantive primers for /education/{slug}.
//
// The point of this surface: most debate motions are about subjects, not
// debate. You can know APDA cold and still lose a tax-policy round
// because you can't tell a Pigovian tax from a Laffer curve. This is the
// primer hub for the domain knowledge that wins motions, not the debate
// theory hub.
//
// Voice rules (mirrors soul.md §5):
//   - Practical over academic. "Inflation eats fixed-income retirees
//     first" beats "monetary policy shifts intertemporal consumption."
//   - No em-dashes anywhere.
//   - Don't name-drop philosophers unless the topic genuinely turns on
//     them. Concepts first, names later (and sparingly).
//   - One memorable line per primer.
//
// Schema (per entry):
//   slug         URL fragment (lowercase, kebab)
//   name         Display name
//   eyebrow      Short category label
//   pitch        1-2 sentence lede explaining what + why a debater
//                cares
//   concepts     [{ term, gloss }] core ideas, 5-8 per topic
//   debateUses   [{ shape, example }] how this shows up in rounds
//   misconceptions [{ wrong, right }] common errors debaters make
//   sampleMotions [string] motions where this knowledge bites
//   deeperReads  [{ title, by, why }] 2-3 substantive next-steps
//   quiz         [{ q, options[4], correct, why }] 5-Q MCQ check.
//                Tests conceptual recall + application, not trivia.
//                Client-side scored in education.mjs; correct/why
//                shown post-answer so the quiz teaches, not just tests.
//   keywords     [string] for SEO meta

export const EDUCATION_BANK = {
  finance: {
    slug: 'finance',
    name: 'Finance & Economics',
    eyebrow: 'Money, markets, policy',
    pitch: 'Most economic motions reward whoever can do the arithmetic out loud. This is the working vocabulary: what makes prices move, what taxes actually do, why interest rates are the lever every government keeps pulling.',
    concepts: [
      { term: 'Inflation',
        gloss: 'Sustained rise in the general price level. Erodes savings, hits fixed-income earners first, pressures central banks to raise rates. "Two percent" is the target most rich-country central banks aim at; above five percent governments start to lose elections.' },
      { term: 'Monetary policy',
        gloss: 'How central banks (Fed, ECB, RBI, BoE) steer the economy by changing interest rates and the money supply. Lower rates = cheaper borrowing = more spending. Raise rates = cool inflation but risk recession.' },
      { term: 'Fiscal policy',
        gloss: 'Government spending and taxation. Expansionary fiscal policy (deficit spending) pumps demand into the economy; contractionary fiscal policy (austerity) does the opposite. Politicians control this; central banks don\'t.' },
      { term: 'Progressive vs regressive taxation',
        gloss: 'Progressive: higher earners pay a higher rate (income tax, capital gains in most countries). Regressive: lower earners pay a higher share of income (sales tax, VAT, lottery, gas tax). Most real tax systems are a mix.' },
      { term: 'Pigovian tax',
        gloss: 'Tax on an activity that creates negative externalities, sized to internalize the harm. Carbon tax is the cleanest example: producer pollutes, society pays for cleanup, tax shifts the cost back to the producer.' },
      { term: 'Market failure',
        gloss: 'Five canonical ones: externalities (pollution), public goods (national defense), monopoly power, information asymmetry (used cars, insurance), and inequity (markets allocate efficiently, not fairly). Most "should the state regulate X" motions live here.' },
      { term: 'Deadweight loss',
        gloss: 'The economic value destroyed when a tax or price control distorts a market away from its efficient point. The standard counter to "just tax it more" arguments: every tax has a deadweight cost beyond the revenue it raises.' },
      { term: 'GDP',
        gloss: 'Total value of goods and services produced in an economy in a year. Measures activity, not welfare. "GDP grew but median wages stagnated" is a sentence you should be ready to back with examples.' },
    ],
    debateUses: [
      { shape: 'Redistribution motions',
        example: '"THBT progressive taxation should fund universal basic income." Live where the disagreement is: gov says income inequality is a market failure markets won\'t self-correct; opp says distortion costs and work-disincentive effects exceed the redistributive gain.' },
      { shape: 'Industry policy / subsidy motions',
        example: '"THW heavily subsidize semiconductor manufacturing." Identify the market failure (national-security externality, dependency on Taiwan), price it, then debate whether subsidies actually fix it or just hand money to incumbents.' },
      { shape: 'Central-bank-independence motions',
        example: '"THW give elected officials direct control over interest rates." The case isn\'t "economists know best"; it\'s about time-inconsistency: politicians have a structural incentive to inflate before elections.' },
      { shape: 'Trade & tariff motions',
        example: '"THBT free trade has, on net, harmed the global working class." Reach for the China shock literature (Autor, Dorn, Hanson) on losers from import competition, not vague "globalization good or bad" platitudes.' },
    ],
    misconceptions: [
      { wrong: '"Printing money always causes inflation."',
        right: 'Money supply matters, but velocity (how fast money changes hands) and expectations matter just as much. Post-2008 QE expanded the monetary base massively without consumer inflation because the new money sat as bank reserves.' },
      { wrong: '"Tax cuts pay for themselves."',
        right: 'Sometimes true at very high marginal rates (Laffer curve right of the peak), basically never true at the rates rich countries actually levy. CBO scoring of every major US tax cut since 1981 shows revenue losses.' },
      { wrong: '"Trade deficits mean a country is losing."',
        right: 'A trade deficit means the country is importing more goods than it exports; it\'s typically balanced by a capital-account surplus (foreigners buying domestic assets). The US runs a persistent trade deficit because the world wants to hold dollars.' },
    ],
    sampleMotions: [
      'THW abolish the corporate income tax and replace it with a higher capital-gains tax.',
      'THBT central bank independence has, on net, harmed democracy.',
      'THW impose a global minimum corporate tax of 25%.',
      'THBT economic growth is no longer a worthwhile policy goal for high-income countries.',
      'THW replace the welfare state with a universal basic income.',
    ],
    deeperReads: [
      { title: 'The Undercover Economist',
        by: 'Tim Harford',
        why: 'Best entry point. Each chapter pegs one economic concept to a real-world thing (Starbucks pricing, used-car markets, hospital scheduling).' },
      { title: 'Capital and Ideology',
        by: 'Thomas Piketty',
        why: 'The data-heaviest argument for redistribution in print. Don\'t quote the whole thing; do know the wealth-concentration numbers.' },
      { title: 'The Wages of Destruction',
        by: 'Adam Tooze',
        why: 'How economic constraints shaped one of the largest policy decisions of the 20th century. Useful for trade-and-war motions.' },
    ],
    quiz: [
      { q: 'What does a Pigovian tax do?',
        options: [
          'Taxes income progressively, with higher earners paying more',
          'Taxes an activity with negative externalities to internalize its social cost',
          'Taxes imports to protect domestic industries from foreign competition',
          'Taxes wealth above a fixed threshold',
        ],
        correct: 1,
        why: 'A Pigovian tax (after economist Arthur Pigou) is sized so producers pay for harms they impose on others — pollution being the classic example. Carbon tax is the contemporary case.' },
      { q: 'Which best describes a regressive tax?',
        options: [
          'Higher earners pay a larger share of their income',
          'Everyone pays the same percentage of income',
          'Lower earners pay a larger share of their income',
          'It only applies to wealth above $1M',
        ],
        correct: 2,
        why: 'Sales taxes, gas taxes, and lotteries are regressive: they take a bigger bite out of low incomes because the rich save a larger fraction of what they earn.' },
      { q: 'A central bank fighting inflation typically does what?',
        options: [
          'Cuts interest rates',
          'Raises interest rates',
          'Cuts taxes',
          'Prints more physical currency',
        ],
        correct: 1,
        why: 'Higher rates make borrowing more expensive, which cools demand and pulls prices back. The Fed, ECB, RBI, BoE all leaned on this lever post-2022.' },
      { q: '"Deadweight loss" refers to:',
        options: [
          'Government revenue lost to tax evasion',
          'Economic value destroyed when a tax or price control distorts a market away from its efficient point',
          'The total cost of an economic depression',
          'Unemployment benefits paid to laid-off workers',
        ],
        correct: 1,
        why: 'Every tax has a cost beyond the revenue raised: some mutually beneficial transactions stop happening. The standard counter to "just tax it more" arguments.' },
      { q: 'Which is NOT one of the five canonical market failures?',
        options: [
          'Externalities (pollution)',
          'Public goods (national defense)',
          'Information asymmetry (used cars, insurance)',
          'Foreign exchange volatility',
        ],
        correct: 3,
        why: 'The canonical five are externalities, public goods, monopoly power, information asymmetry, and inequity. Currency fluctuation is a separate macro phenomenon.' },
    ],
    keywords: ['finance for debate', 'economics primer', 'taxation debate', 'monetary policy debate prep', 'fiscal policy', 'market failure', 'inflation explained'],
  },

  'feminist-theory': {
    slug: 'feminist-theory',
    name: 'Feminist Theory',
    eyebrow: 'Gender, power, equity',
    pitch: 'Gender motions get cooked when one side treats "feminism" as a single position. It\'s four overlapping traditions with real internal disagreements. Knowing which one you\'re standing on is the difference between a real case and a slogan.',
    concepts: [
      { term: 'First-wave feminism',
        gloss: 'Roughly 1840s-1920s. The legal-rights wave: suffrage, property ownership, the right to divorce, the right to sit on a jury. Resolved most of its targets in rich democracies by mid-century.' },
      { term: 'Second-wave feminism',
        gloss: '1960s-1980s. Moved past formal-legal equality to "the personal is political": workplace equality, reproductive rights, sexual harassment law, domestic-violence policy. This is the wave that shaped most current Western family law.' },
      { term: 'Third-wave feminism',
        gloss: '1990s onward. Pluralism over universalism: pushed back on the assumption that "women" was a single political category and that white middle-class concerns spoke for everyone. Where the intersectional turn lives.' },
      { term: 'Intersectionality',
        gloss: 'The idea that gender oppression compounds with race, class, sexuality, and disability in ways you can\'t just add up. A Black woman doesn\'t face "racism plus sexism"; she faces a distinct experience the additive frame misses. Coined by Kimberlé Crenshaw in 1989.' },
      { term: 'Liberal vs radical vs Marxist feminism',
        gloss: 'Liberal: integrate women into existing institutions, fix the rules so they\'re neutral. Radical: the institutions themselves are gendered; integration isn\'t enough. Marxist: gender oppression is downstream of class oppression, and you can\'t fix one without the other. Most contemporary policy debate sits in tension between the first two.' },
      { term: 'Care economy',
        gloss: 'Unpaid domestic and caregiving work, disproportionately done by women, valued at roughly 10-39% of GDP depending on country and method. Most feminist economic arguments anchor here: the economy externalizes care onto unpaid labor.' },
      { term: 'Glass ceiling vs sticky floor',
        gloss: 'Glass ceiling: the barrier women hit moving into elite roles. Sticky floor: the cluster of low-wage feminized industries (care work, retail, hospitality) where most working women actually are. Policy that breaks the ceiling often doesn\'t touch the floor.' },
        { term: 'Choice feminism (and the critique)',
          gloss: 'The idea that any choice a woman makes is feminist because she made it. The standard critique: choices are made inside structures, so "I chose to leave my career" is still shaped by the absence of childcare, paid leave, and male partners doing equal housework.' },
    ],
    debateUses: [
      { shape: 'Workplace-policy motions',
        example: '"THW mandate that public companies have boards at least 40% women." Pick your lane: liberal-feminist case (equal access to elite positions matters intrinsically and corrects bias-driven misallocation) vs critique (helps a small elite while leaving the sticky floor untouched).' },
      { shape: 'Family-policy motions',
        example: '"THW require an equal split of parental leave between parents." Case turns on whether you think the care economy is a women\'s problem (let women decide) or a structural problem (the rules incentivize unequal splits, change the rules).' },
      { shape: 'Representation motions',
        example: '"THBT feminism, as currently practiced in the West, has failed working-class women." Intersectional case: the movement\'s wins concentrate in professional-managerial occupations; minimum-wage care workers got little of it.' },
      { shape: 'Identity / definition motions',
        example: '"THBT trans women are women." This is a metaphysical and political claim simultaneously; the strongest cases on both sides cite different feminist traditions on what "woman" categorizes.' },
    ],
    misconceptions: [
      { wrong: '"All feminists agree about [X]."',
        right: 'Liberal feminists, radical feminists, intersectional feminists, and ecofeminists disagree on most current policy questions. Naming which strand you\'re defending is more persuasive than waving "feminism" as a bloc.' },
      { wrong: '"Feminism is about hating men."',
        right: 'No serious feminist tradition argues this. The closest is some second-wave radical feminism arguing that patriarchy as a system harms men too (limits emotional range, channels them into violence and risk).' },
      { wrong: '"The gender pay gap is just women choosing lower-paid careers."',
        right: 'About 60% of the raw gap is explained by occupation, hours, and experience. The remaining 40% (the "adjusted" gap, ~6-10 percentage points in most rich countries) is what economists can\'t explain with anything but discrimination or career disruption from caregiving.' },
    ],
    sampleMotions: [
      'THBT feminist movements should prioritize the care economy over corporate-boardroom representation.',
      'THW criminalize the purchase, but not the sale, of sex (Nordic model).',
      'THBT the gender pay gap is primarily a problem of unpaid care work, not workplace discrimination.',
      'THW require all custody disputes to begin with a default 50-50 split.',
      'THBT intersectional feminism has, on net, weakened the political coalition for women\'s rights.',
    ],
    deeperReads: [
      { title: 'Invisible Women',
        by: 'Caroline Criado Perez',
        why: 'How everything from drug dosing to seatbelt design to office temperatures defaults to male physiology. Hardest-hitting fact-bank for "structural sexism" arguments in print.' },
      { title: 'Why I\'m No Longer Talking to White People About Race',
        by: 'Reni Eddo-Lodge',
        why: 'Best short read on intersectionality if you want to see why race and gender don\'t add up linearly.' },
      { title: 'The Second Sex',
        by: 'Simone de Beauvoir',
        why: 'The book second-wave feminism is built on top of. Long; read the introduction and the chapter "Woman: Myth and Reality" if nothing else.' },
    ],
    quiz: [
      { q: 'Intersectionality argues that:',
        options: [
          'All women face essentially the same oppression',
          'Race and gender oppression can be added together linearly',
          'Gender oppression compounds with race, class, and sexuality in non-additive ways',
          'Feminism is not relevant to women of color',
        ],
        correct: 2,
        why: 'Coined by Kimberlé Crenshaw in 1989. A Black woman doesn\'t face "racism plus sexism" — she faces a distinct experience the additive frame misses.' },
      { q: 'Which wave of feminism focused on suffrage and legal property rights?',
        options: ['First wave', 'Second wave', 'Third wave', 'Fourth wave'],
        correct: 0,
        why: 'First-wave feminism (1840s-1920s) targeted formal legal rights including the vote, property ownership, and access to divorce.' },
      { q: 'The "care economy" refers to:',
        options: [
          'Government welfare spending',
          'Unpaid domestic and caregiving work, disproportionately done by women',
          'The healthcare and elder-care industries',
          'Private daycare and nanny services',
        ],
        correct: 1,
        why: 'Estimates put unpaid care work at 10-39% of GDP. Most feminist economic critiques anchor here: the economy externalizes care onto unpaid labor.' },
      { q: 'Liberal feminism differs from radical feminism in that:',
        options: [
          'Liberal feminism rejects equal rights',
          'Liberal feminism wants women integrated into existing institutions; radical feminism says those institutions are themselves gendered',
          'Radical feminism only addresses race',
          'The two positions are functionally synonymous',
        ],
        correct: 1,
        why: 'This split is the core of most current policy disagreement inside feminism. Liberal: fix the rules. Radical: the rules aren\'t the problem; the institutions are.' },
      { q: 'After controlling for hours, occupation, and experience, the "adjusted" gender pay gap in most rich countries is roughly:',
        options: ['0%', '6-10 percentage points', '20-25 percentage points', '50%'],
        correct: 1,
        why: 'The raw gap is ~16-18% in most rich countries; ~60% of that is explained by occupation and hours. The unexplained adjusted gap — likely discrimination plus caregiving career disruption — is ~6-10 percentage points.' },
    ],
    keywords: ['feminist theory debate', 'intersectionality primer', 'gender motions debate prep', 'care economy', 'feminist economics', 'liberal feminism radical feminism'],
  },

  'international-relations': {
    slug: 'international-relations',
    name: 'International Relations',
    eyebrow: 'States, power, war and peace',
    pitch: 'IR motions reward knowing the three or four schools that fight over every foreign-policy question. Once you can place a motion inside "realist vs liberal vs constructivist," the warrants come fast.',
    concepts: [
      { term: 'Realism',
        gloss: 'States are the primary actors, the international system is anarchic (no global government), and each state pursues its own security. Cooperation is fragile; alliances shift as power shifts. Most foreign-policy hawks reach for realism by default.' },
      { term: 'Liberalism (in IR)',
        gloss: 'States cooperate through institutions (UN, WTO, NATO), trade creates mutual interest, and democracies are less likely to fight each other. The "rules-based international order" is a liberal-IR phrase.' },
      { term: 'Constructivism',
        gloss: 'Identity and norms shape state behavior, not just material power. Why doesn\'t Canada arm against the US? Not because they can\'t; because the relationship\'s identity-construction makes war unthinkable. Useful for motions about norms (human rights, nuclear non-proliferation).' },
      { term: 'Hegemony',
        gloss: 'A single dominant power that sets the rules. Pax Britannica (19th century), Pax Americana (post-1945). "Hegemonic decline" arguments turn on whether US relative power loss leads to instability (realist) or institutional inertia (liberal).' },
      { term: 'Sovereignty',
        gloss: 'A state\'s right to govern its territory without outside interference. Tension point in any humanitarian-intervention motion: do human-rights norms override sovereignty, and who decides?' },
      { term: 'Security dilemma',
        gloss: 'When one state\'s defensive buildup looks offensive to its neighbor, who arms in response, which looks offensive to the first state. Most arms races and pre-war spirals trace through this.' },
      { term: 'Soft power',
        gloss: 'Power through attraction rather than coercion: culture, education, alliance value. The reason South Korea\'s K-pop matters for its security. Coined by Joseph Nye in 1990.' },
      { term: 'Balance of power vs bandwagoning',
        gloss: 'When a rising power emerges, smaller states either balance against it (form alliances to constrain it) or bandwagon with it (join its orbit for the spoils). Most current "China rises, what does Vietnam do" motions live here.' },
    ],
    debateUses: [
      { shape: 'Intervention motions',
        example: '"THW intervene militarily in [country] to stop a humanitarian crisis." The classic realist-vs-liberal-vs-constructivist three-way. Realist: doesn\'t serve national interest, don\'t go. Liberal: international institutions and R2P norms demand it. Constructivist: the norm of non-intervention is itself contested and shifting.' },
      { shape: 'Alliance motions',
        example: '"THW dissolve NATO." Realist case for: alliance is a relic, antagonizes Russia, drags US into unnecessary wars. Liberal case against: institutions create predictability, dissolving signals weakness, reopens great-power conflict.' },
      { shape: 'Trade-as-foreign-policy motions',
        example: '"THW use trade sanctions against [authoritarian state]." Sanctions literature is mixed: rarely change regime behavior, often hurt civilians most, sometimes the only non-military tool. Naming the empirical record beats moral framing.' },
      { shape: 'Great-power-competition motions',
        example: '"THBT the US should accommodate, rather than contain, China." Containment vs engagement is the foreign-policy debate of the next decade. Have a position. Be ready for the security-dilemma cross-application.' },
    ],
    misconceptions: [
      { wrong: '"The UN is irrelevant."',
        right: 'The UN Security Council is constrained by the P5 veto, yes. But UN agencies (WHO, UNHCR, UNICEF, IAEA) and peacekeeping operations move serious resources and have prevented or shortened many conflicts the council couldn\'t touch.' },
      { wrong: '"Democracies don\'t fight each other."',
        right: 'Mostly true since 1945. But there are edge cases, the definition of "democracy" is doing real work, and the mechanism (trade, institutional constraints, shared identity) is contested. Don\'t cite this as a law; cite it as a strong tendency.' },
      { wrong: '"Sanctions don\'t work."',
        right: 'Sanctions targeted at specific elites and connected to specific behavioral changes have a moderate success rate (40-50% in some datasets). Broad-population sanctions have a poor record. Specify which kind.' },
    ],
    sampleMotions: [
      'THBT the United States should accept the loss of its hegemonic position.',
      'THW dissolve NATO.',
      'THBT economic interdependence makes war less likely.',
      'THW give the UN Security Council the power to override state sovereignty in cases of mass atrocity.',
      'THBT non-proliferation is no longer a serious foreign-policy priority.',
    ],
    deeperReads: [
      { title: 'The Tragedy of Great Power Politics',
        by: 'John Mearsheimer',
        why: 'The strongest single statement of offensive realism. Disagree with it if you want; you should know what you\'re disagreeing with.' },
      { title: 'The End of History and the Last Man',
        by: 'Francis Fukuyama',
        why: 'The famous liberal-IR thesis. Aged unevenly, which is itself useful: the parts that aged badly tell you what realism has to say about the parts that aged well.' },
      { title: 'A Problem from Hell',
        by: 'Samantha Power',
        why: 'On the policy machinery of humanitarian intervention and non-intervention. Read this before any genocide-related motion.' },
    ],
    quiz: [
      { q: 'Realism in IR primarily argues:',
        options: [
          'States cooperate through international institutions',
          'States act on identities and shared norms',
          'States pursue security in an anarchic international system',
          'International law constrains state behavior tightly',
        ],
        correct: 2,
        why: 'Realism\'s two foundational premises: anarchy (no global government) and security-seeking. Most foreign-policy hawks reach for realism by default.' },
      { q: 'The "security dilemma" describes what happens when:',
        options: [
          'Two states ally against a third',
          'One state\'s defensive buildup looks offensive to its neighbor, triggering an arms race',
          'A state lacks the budget to defend itself',
          'Nuclear states threaten non-nuclear states',
        ],
        correct: 1,
        why: 'A classic spiral mechanism. Defense intentions are unobservable; arms aren\'t. Pre-WWI Europe is the textbook case.' },
      { q: '"Soft power" refers to:',
        options: [
          'Military power held in reserve',
          'Power through attraction (culture, alliances, education) rather than coercion',
          'Power exercised without nuclear weapons',
          'Diplomatic immunity for embassy staff',
        ],
        correct: 1,
        why: 'Coined by Joseph Nye in 1990. The reason K-pop matters for South Korea\'s security position — the world wants what Korea makes, that\'s leverage.' },
      { q: 'When a smaller state aligns with a rising power rather than balancing against it, this is called:',
        options: ['Containment', 'Hegemony', 'Bandwagoning', 'Engagement'],
        correct: 2,
        why: 'Balancing and bandwagoning are the two main strategies smaller states pursue toward rising powers. Most "what does Vietnam do about China" motions live here.' },
      { q: 'The "democratic peace" thesis claims that:',
        options: [
          'All democracies are pacifist',
          'Democracies are less likely to fight other democracies',
          'Democracies have never gone to war',
          'Democracies always win the wars they fight',
        ],
        correct: 1,
        why: 'A strong empirical tendency since 1945, not a law. Mechanisms (trade, institutions, identity) are still actively debated.' },
    ],
    keywords: ['international relations debate', 'IR theory primer', 'realism liberalism constructivism', 'foreign policy motions', 'sovereignty debate', 'security dilemma'],
  },

  'climate-policy': {
    slug: 'climate-policy',
    name: 'Climate Policy',
    eyebrow: 'Mitigation, adaptation, costs',
    pitch: 'Climate motions are won by whoever does the actual policy comparison out loud. The science is settled; the disagreement is about which lever (tax, subsidy, regulation, treaty, geoengineering) does the most per dollar, and who pays.',
    concepts: [
      { term: 'Mitigation vs adaptation',
        gloss: 'Mitigation: reduce emissions to limit future warming. Adaptation: prepare for the warming already locked in. Most policy is mitigation-flavored; the adaptation conversation matters more every year the world overshoots its mitigation targets.' },
      { term: 'Carbon pricing',
        gloss: 'Two flavors: a carbon tax (set the price, market chooses the quantity) and cap-and-trade (set the quantity, market chooses the price). Economists prefer one or the other; political feasibility usually picks cap-and-trade because the cost is opaque.' },
      { term: 'Net-zero targets',
        gloss: 'Emissions cut to whatever can be balanced by removals (forests, direct-air capture, soil sequestration). Almost every rich country has a 2050 net-zero pledge; almost none are on track.' },
      { term: 'Loss and damage',
        gloss: 'Compensation from rich-country emitters to poor-country victims for climate harms that have already happened. The COP27 wedge issue. Distinct from adaptation funding (preparing for future harm) and mitigation finance (cutting emissions).' },
      { term: 'Just transition',
        gloss: 'A decarbonization path that doesn\'t collapse the coal-town, oil-state, gas-driver economies on the way. Often the political pivot that makes mitigation possible.' },
      { term: 'Geoengineering',
        gloss: 'Direct intervention in the climate system. Two families: carbon-dioxide removal (slow, expensive, low-risk) and solar radiation management (fast, cheap, high-risk). The latter is what people mean when they say "geoengineering is dangerous."' },
      { term: 'Tipping points',
        gloss: 'Thresholds past which climate damage becomes self-reinforcing: Amazon dieback, Greenland ice-sheet collapse, permafrost methane release. The reason "we can adapt" arguments get weaker each year.' },
      { term: 'Common but differentiated responsibilities',
        gloss: 'UNFCCC principle: all states have a duty to act on climate, but rich states (historical emitters) have a bigger one. The pivot of every North-South climate disagreement.' },
    ],
    debateUses: [
      { shape: 'Pricing motions',
        example: '"THW impose a global carbon tax of $100/tonne." Standard economic case is strong; political-feasibility opp turns on regressive impact on poor consumers and competitiveness loss versus non-pricing trade partners.' },
      { shape: 'Loss-and-damage motions',
        example: '"THBT rich nations have an unconditional duty to compensate climate-vulnerable nations." Pick a frame: historical-responsibility (you broke it, you bought it), capacity-to-pay (the marginal cost falls more on the poor), or institutional (compensation makes future cooperation impossible).' },
      { shape: 'Technology motions',
        example: '"THW deploy solar-radiation-management geoengineering." The cleanest moral-hazard motion in the format. Gov: science says it works, costs are negligible, every year of delay is more dead people. Opp: changes monsoon patterns, creates a termination shock, sets up unilateral deployment by a single state.' },
      { shape: 'Justice motions',
        example: '"THBT the climate movement should prioritize Global South adaptation over Global North mitigation." Reframes the whole debate: the people most harmed are not the people whose emissions are at stake, and the dollar-per-life-saved math points to adaptation finance.' },
    ],
    misconceptions: [
      { wrong: '"Renewables are too expensive."',
        right: 'Solar PV is now the cheapest source of electricity in most regions of the world per the IEA. The cost of new solar fell ~90% from 2010 to 2024. The expensive parts are storage and grid upgrades, not generation.' },
      { wrong: '"Individual action solves climate change."',
        right: 'Personal lifestyle changes are necessary but quantitatively small. About 70% of emissions come from 100 companies (Carbon Majors data). The lever that moves at the right scale is policy, not consumer choice.' },
      { wrong: '"Nuclear is too dangerous."',
        right: 'Per-terawatt-hour of energy produced, nuclear has roughly the same death rate as wind or solar (Our World in Data, citing Markandya and Wilkinson). Coal kills hundreds of times more people per TWh, mostly through air pollution.' },
    ],
    sampleMotions: [
      'THW impose a globally uniform carbon tax of $100/tonne.',
      'THBT solar-radiation-management research should be banned.',
      'THW make rich nations legally liable for climate-induced migration from poor nations.',
      'THBT the environmental movement should embrace nuclear power.',
      'THW require all new fossil-fuel projects to demonstrate climate compatibility before receiving permits.',
    ],
    deeperReads: [
      { title: 'How to Avoid a Climate Disaster',
        by: 'Bill Gates',
        why: 'Best policy-mechanic walkthrough of the green premium concept (what does decarbonization actually cost per sector) you\'ll find under 250 pages.' },
      { title: 'The Uninhabitable Earth',
        by: 'David Wallace-Wells',
        why: 'The catastrophe scenario in full. Read this AFTER something less alarmed so you can calibrate.' },
      { title: 'IPCC AR6 Synthesis Report (Summary for Policymakers)',
        by: 'IPCC',
        why: 'The 30-page consensus document the rest of the conversation is arguing about. Free, public, current.' },
    ],
    quiz: [
      { q: 'Mitigation and adaptation in climate policy are:',
        options: [
          'Two terms for the same approach',
          'Mitigation = cut emissions; adaptation = prepare for warming already locked in',
          'Adaptation is for poor countries; mitigation is for rich ones',
          'Both refer to renewable-energy deployment',
        ],
        correct: 1,
        why: 'As the world overshoots mitigation targets, the adaptation conversation gets more central every year — but they\'re distinct policy levers.' },
      { q: 'A carbon tax and cap-and-trade differ in that:',
        options: [
          'One uses solar; the other uses wind',
          'Carbon tax sets the price and lets the market choose the quantity; cap-and-trade sets the quantity and lets the market choose the price',
          'They are economically identical in every way',
          'Only cap-and-trade applies to industrial emitters',
        ],
        correct: 1,
        why: 'They achieve the same outcome in theory. Politics usually picks cap-and-trade because the cost to consumers is opaque, unlike a visible tax line.' },
      { q: '"Loss and damage" funding refers to:',
        options: [
          'Private insurance against extreme-weather events',
          'Compensation from rich-country emitters to poor-country victims for climate harms that already happened',
          'Subsidies for renewable-energy projects',
          'Aid for refugees from any cause',
        ],
        correct: 1,
        why: 'Distinct from adaptation finance (future harm) and mitigation finance (emissions cuts). The COP27 wedge issue.' },
      { q: 'Per terawatt-hour of energy produced, which has the highest death rate?',
        options: ['Nuclear', 'Wind', 'Solar', 'Coal'],
        correct: 3,
        why: 'Coal kills hundreds of times more people per TWh than nuclear, wind, or solar — mostly through air-pollution-driven respiratory and cardiovascular disease (Our World in Data, citing Markandya and Wilkinson).' },
      { q: '"Just transition" refers to:',
        options: [
          'Carbon-offset trading markets',
          'A decarbonization path that doesn\'t economically collapse coal, oil, and gas-dependent communities',
          'International climate-court rulings',
          'Treating all countries identically regardless of emissions history',
        ],
        correct: 1,
        why: 'Often the political pivot that makes mitigation possible at all. Without it, coal-town backlash kills the policy before it ships.' },
    ],
    keywords: ['climate policy debate', 'carbon tax explained', 'climate motions prep', 'mitigation adaptation', 'loss and damage', 'just transition', 'geoengineering debate'],
  },
};

export function getEducationTopic(slug) {
  return EDUCATION_BANK[slug] || null;
}

export const EDUCATION_SLUGS = Object.keys(EDUCATION_BANK);
