// AUTO-BAKED from Tabroom public records (~/debateit-outreach), 2026-07-02.
// Public data only: school/program names + state + formats + activity. NO coach or judge names, NO emails.
export const PROGRAMS = [
  { n:"Montgomery Academy", st:"AL", fmts:["Policy","LD","PF","Congress","World Schools","Big Questions","Speech"], act:51, t:3, seen:"2026" },
  { n:"Russellville High School", st:"AL", act:31, t:1, seen:"2025" },
  { n:"The Altamont School", st:"AL", fmts:["Congress","World Schools","Big Questions","Speech"], act:28, t:1, seen:"2026" },
  { n:"Oxford HS", st:"AL", act:25, t:1, seen:"2025" },
  { n:"Artemis Debate", st:"AL", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:24, t:2, seen:"2026" },
  { n:"Cabot High School", st:"AR", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:86, t:4, seen:"2026" },
  { n:"Conway High School", st:"AR", act:14, t:1, seen:"2025" },
  { n:"BASIS Peoria", st:"AZ", fmts:["Policy","LD","PF","Congress","World Schools","Speech"], act:86, t:3, seen:"2026" },
  { n:"Arizona Chandler Independent", st:"AZ", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:51, t:2, seen:"2026" },
  { n:"Phoenix Country Day School", st:"AZ", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:47, t:3, seen:"2026" },
  { n:"McClintock High School", st:"AZ", fmts:["Policy","LD","Speech"], act:26, t:1, seen:"2026" },
  { n:"Arizona College Prep Middle School", st:"AZ", fmts:["Congress","World Schools","Big Questions","Speech"], act:14, t:1, seen:"2026" },
  { n:"Ascend Academy", st:"AZ", fmts:["Congress","World Schools","Big Questions","Speech"], act:13, t:1, seen:"2026" },
  { n:"Hamilton High School", st:"AZ", fmts:["Policy","LD","Congress","World Schools","Speech"], act:11, t:1, seen:"2026" },
  { n:"Independent Hamilton High School", st:"AZ", act:10, t:1, seen:"2026" },
  { n:"Los Altos High School", st:"CA", fmts:["Policy","LD","Parli","Congress","World Schools","Big Questions","Speech"], act:594, t:19, seen:"2026" },
  { n:"The Nueva School", st:"CA", fmts:["Policy","LD","Parli","Congress","World Schools","Big Questions","Speech"], act:578, t:19, seen:"2026" },
  { n:"Berkeley High School", st:"CA", fmts:["Policy","Parli","Congress","World Schools","Speech"], act:576, t:26, seen:"2026" },
  { n:"Irvington HS", st:"CA", fmts:["Policy","Parli","Congress","World Schools","Big Questions","Speech"], act:549, t:27, seen:"2026" },
  { n:"The Quarry Lane School", st:"CA", fmts:["Policy","LD","Parli","Congress","World Schools","Big Questions","Speech"], act:537, t:7, seen:"2026" },
  { n:"Palo Alto High School", st:"CA", fmts:["Policy","LD","Parli","Congress","World Schools","Big Questions","Speech"], act:534, t:17, seen:"2027" },
  { n:"Dougherty Valley High School", st:"CA", fmts:["Policy","LD","Parli","Congress","World Schools","Big Questions","Speech"], act:505, t:6, seen:"2026" },
  { n:"Menlo-Atherton High School", st:"CA", fmts:["Policy","Parli","Congress","World Schools","Big Questions","Speech"], act:470, t:32, seen:"2026" },
  { n:"Monta Vista High School", st:"CA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:437, t:4, seen:"2026" },
  { n:"Bellarmine College Preparatory", st:"CA", fmts:["Policy","LD","Parli","Congress","World Schools","Big Questions","Speech"], act:385, t:4, seen:"2026" },
  { n:"Monte Vista", st:"CA", fmts:["Policy","LD","Parli","Congress","World Schools","Speech"], act:376, t:5, seen:"2026" },
  { n:"Washington High School", st:"CA", fmts:["Policy","LD","Parli","Congress","World Schools","Big Questions","Speech"], act:374, t:19, seen:"2026" },
  { n:"The Harker School", st:"CA", fmts:["Policy","LD","PF","Congress","World Schools","Speech"], act:366, t:3, seen:"2026" },
  { n:"Leland High School", st:"CA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:337, t:3, seen:"2026" },
  { n:"Miramonte High School", st:"CA", fmts:["Policy","LD","Parli","Congress","World Schools","Big Questions","Speech"], act:327, t:7, seen:"2026" },
  { n:"James Logan High School", st:"CA", fmts:["Policy","LD","Parli","Congress","World Schools","Big Questions","Speech"], act:322, t:6, seen:"2026" },
  { n:"Archbishop Mitty", st:"CA", fmts:["Policy","LD","Parli","Congress","World Schools","Big Questions","Speech"], act:321, t:7, seen:"2027" },
  { n:"Mountain View High School", st:"CA", fmts:["Policy","LD","Parli","Congress","World Schools","Big Questions","Speech"], act:300, t:16, seen:"2026" },
  { n:"Dougherty Valley Bridge", st:"CA", fmts:["Congress","World Schools","Big Questions","Speech"], act:286, t:3, seen:"2026" },
  { n:"Milpitas", st:"CA", fmts:["Policy","LD","Parli","Congress","World Schools","Big Questions","Speech"], act:282, t:9, seen:"2026" },
  { n:"Loyola High School", st:"CA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:264, t:5, seen:"2026" },
  { n:"Papaya Valley", st:"CA", fmts:["Policy","Parli","Congress","World Schools","Big Questions","Speech"], act:230, t:13, seen:"2026" },
  { n:"El Cerrito", st:"CA", fmts:["Policy","LD","Parli","Congress","World Schools","Speech"], act:228, t:18, seen:"2026" },
  { n:"Campolindo High School", st:"CA", fmts:["Congress","World Schools","Big Questions","Speech"], act:224, t:20, seen:"2026" },
  { n:"Ridge High School", st:"CA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:217, t:12, seen:"2026" },
  { n:"Princeton", st:"CA", fmts:["Speech"], act:209, t:17, seen:"2026" },
  { n:"Las Lomas High School", st:"CA", fmts:["Policy","Parli","Congress","World Schools","Big Questions","Speech"], act:205, t:6, seen:"2026" },
  { n:"Menlo School", st:"CA", fmts:["Congress","World Schools","Big Questions","Speech"], act:200, t:21, seen:"2026" },
  { n:"Carlmont High School", st:"CA", fmts:["Policy","LD","Parli","Congress","World Schools","Big Questions","Speech"], act:200, t:15, seen:"2026" },
  { n:"Lowell High School", st:"CA", fmts:["Policy","Parli","Congress","World Schools","Speech"], act:190, t:8, seen:"2026" },
  { n:"Able2Shine", st:"CA", fmts:["Congress","World Schools","Big Questions","Speech"], act:186, t:3, seen:"2026" },
  { n:"Marlborough School", st:"CA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:182, t:3, seen:"2026" },
  { n:"Honor Academy", st:"CA", fmts:["Congress","World Schools","Big Questions","Speech"], act:176, t:5, seen:"2026" },
  { n:"College Prep", st:"CA", fmts:["Policy","LD","Parli","Congress","World Schools","Big Questions","Speech"], act:171, t:7, seen:"2026" },
  { n:"Cupertino High School", st:"CA", fmts:["Policy","LD","Parli","Congress","World Schools","Big Questions","Speech"], act:168, t:3, seen:"2026" },
  { n:"San Marino High School", st:"CA", fmts:["Policy","LD","Parli","Congress","World Schools","Big Questions","Speech"], act:167, t:7, seen:"2026" },
  { n:"Tierra Linda Middle School", st:"CA", fmts:["Congress","World Schools","Big Questions","Speech"], act:161, t:4, seen:"2026" },
  { n:"Harvard-Westlake School", st:"CA", fmts:["Policy","LD","PF","Congress","World Schools","Big Questions","Speech"], act:159, t:7, seen:"2027" },
  { n:"Valley Christian High School", st:"CA", fmts:["Policy","LD","Parli","Congress","World Schools","Big Questions","Speech"], act:150, t:5, seen:"2026" },
  { n:"Emerald High School", st:"CA", fmts:["Policy","LD","PF","Congress","World Schools","Big Questions","Speech"], act:142, t:4, seen:"2026" },
  { n:"Westwood", st:"CA", fmts:["Policy","LD","PF","Congress","World Schools","Big Questions","Speech"], act:142, t:5, seen:"2026" },
  { n:"Hillbrook", st:"CA", fmts:["Policy","Parli","Congress","World Schools","Big Questions","Speech"], act:137, t:9, seen:"2026" },
  { n:"Notre Dame San Jose", st:"CA", fmts:["Policy","LD","Parli","Congress","World Schools","Big Questions","Speech"], act:130, t:6, seen:"2026" },
  { n:"Tessellations", st:"CA", fmts:["Congress","World Schools","Big Questions","Speech"], act:130, t:8, seen:"2026" },
  { n:"Canyon Crest Academy", st:"CA", fmts:["Policy","LD","PF","Parli","Congress","World Schools","Speech"], act:129, t:12, seen:"2026" },
  { n:"Peninsula High School", st:"CA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:128, t:4, seen:"2026" },
  { n:"George Washington HS", st:"CA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:126, t:3, seen:"2026" },
  { n:"Vista Del Lago High School", st:"CA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:124, t:4, seen:"2026" },
  { n:"Gabrielino High School", st:"CA", fmts:["Congress","World Schools","Big Questions","Speech"], act:119, t:1, seen:"2026" },
  { n:"American High", st:"CA", fmts:["Policy","LD","Parli","Congress","World Schools","Big Questions","Speech"], act:116, t:4, seen:"2026" },
  { n:"Lynbrook HS", st:"CA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:109, t:3, seen:"2026" },
  { n:"Cajon High School", st:"CA", fmts:["Congress","World Schools","Big Questions","Speech"], act:104, t:4, seen:"2026" },
  { n:"Flintridge Preparatory", st:"CA", fmts:["Policy","LD","PF","Congress","World Schools","Big Questions","Speech"], act:103, t:4, seen:"2026" },
  { n:"San Ramon Academy", st:"CA", fmts:["Policy","Parli"], act:102, t:3, seen:"2026" },
  { n:"Polytechnic School", st:"CA", fmts:["Policy","LD","PF","Congress","World Schools","Big Questions","Speech"], act:99, t:9, seen:"2026" },
  { n:"Mission San Jose High School", st:"CA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:99, t:3, seen:"2026" },
  { n:"St. Ignatius College Preparatory", st:"CA", fmts:["Policy","Parli"], act:97, t:2, seen:"2026" },
  { n:"Carlsbad High School", st:"CA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:96, t:5, seen:"2026" },
  { n:"Windward School", st:"CA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:90, t:8, seen:"2026" },
  { n:"BC Academy", st:"CA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:86, t:3, seen:"2026" },
  { n:"Evergreen Valley", st:"CA", fmts:["Policy","LD","Congress","World Schools","Speech"], act:86, t:7, seen:"2026" },
  { n:"Cranbrook", st:"CA", fmts:["Policy","LD","PF","Congress","World Schools","Big Questions","Speech"], act:84, t:4, seen:"2026" },
  { n:"Redlands High School", st:"CA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:82, t:5, seen:"2026" },
  { n:"San Marin", st:"CA", fmts:["Policy","Parli"], act:81, t:4, seen:"2026" },
  { n:"Los Altos - Hacienda Heights", st:"CA", fmts:["Policy","LD","Congress","Speech"], act:79, t:3, seen:"2026" },
  { n:"Troy High School", st:"CA", fmts:["Policy","Parli","Congress","World Schools","Speech"], act:78, t:7, seen:"2026" },
  { n:"King School", st:"CA", fmts:["Parli"], act:77, t:6, seen:"2026" },
  { n:"Bentley School", st:"CA", fmts:["Policy","Parli"], act:72, t:4, seen:"2026" },
  { n:"Bishop O'Dowd High School", st:"CA", fmts:["Policy","Parli"], act:72, t:6, seen:"2026" },
  { n:"Crystal Springs Uplands School", st:"CA", fmts:["Speech"], act:71, t:8, seen:"2026" },
  { n:"San Ramon Valley High School", st:"CA", fmts:["Policy","Parli"], act:70, t:3, seen:"2026" },
  { n:"Castilleja School", st:"CA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:70, t:4, seen:"2026" },
  { n:"North Allegheny", st:"CA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:70, t:5, seen:"2026" },
  { n:"University High School", st:"CA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:69, t:5, seen:"2026" },
  { n:"Granite Bay High School", st:"CA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:69, t:9, seen:"2026" },
  { n:"Saratoga HS", st:"CA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:66, t:5, seen:"2026" },
  { n:"Wilson HS Hacienda Heights", st:"CA", fmts:["Policy","LD","Congress","Speech"], act:64, t:3, seen:"2026" },
  { n:"Los Osos High School", st:"CA", fmts:["Policy","LD","Congress","World Schools","Speech"], act:56, t:2, seen:"2026" },
  { n:"Presentation High School", st:"CA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:55, t:3, seen:"2026" },
  { n:"Abraham Lincoln High School", st:"CA", fmts:["Policy","Parli"], act:55, t:4, seen:"2026" },
  { n:"Foothill Independent", st:"CA", act:52, t:1, seen:"2026" },
  { n:"La Salle College Preparatory", st:"CA", fmts:["Policy","LD","Congress","World Schools","Speech"], act:50, t:5, seen:"2026" },
  { n:"George Washington High School", st:"CA", fmts:["Policy","Parli"], act:50, t:3, seen:"2026" },
  { n:"Piedmont High School", st:"CA", fmts:["Speech"], act:50, t:3, seen:"2026" },
  { n:"Mira Loma High School", st:"CA", fmts:["Policy","LD","Congress","World Schools","Speech"], act:50, t:2, seen:"2026" },
  { n:"Saint Francis High School", st:"CA", act:47, t:2, seen:"2026" },
  { n:"Campbell Hall", st:"CA", fmts:["Policy","LD","PF","Congress","World Schools","Big Questions","Speech"], act:47, t:5, seen:"2026" },
  { n:"Alhambra High School", st:"CA", fmts:["Congress"], act:45, t:1, seen:"2025" },
  { n:"Prospect High School", st:"CA", fmts:["Speech"], act:45, t:4, seen:"2026" },
  { n:"Davis Senior High School", st:"CA", fmts:["Policy","LD","Congress","World Schools","Speech"], act:45, t:2, seen:"2026" },
  { n:"Valencia HS - Placentia", st:"CA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:44, t:4, seen:"2026" },
  { n:"Orosi High School", st:"CA", act:44, t:1, seen:"2026" },
  { n:"Corona del Mar High School", st:"CA", fmts:["Speech"], act:44, t:1, seen:"2025" },
  { n:"Folsom High School", st:"CA", fmts:["Congress","World Schools","Big Questions","Speech"], act:40, t:3, seen:"2026" },
  { n:"Oak Park High School", st:"CA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:40, t:4, seen:"2026" },
  { n:"Livermore High School", st:"CA", fmts:["Parli"], act:39, t:3, seen:"2026" },
  { n:"Santiago High School", st:"CA", fmts:["Congress"], act:39, t:1, seen:"2025" },
  { n:"Etiwanda High School", st:"CA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:38, t:4, seen:"2026" },
  { n:"Piedmont Middle School", st:"CA", fmts:["Congress","World Schools","Big Questions","Speech"], act:38, t:3, seen:"2026" },
  { n:"Laurel School", st:"CA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:37, t:3, seen:"2026" },
  { n:"Khan Lab School", st:"CA", fmts:["Speech"], act:37, t:2, seen:"2026" },
  { n:"San Leandro High School", st:"CA", act:37, t:3, seen:"2026" },
  { n:"Amador Valley Independent", st:"CA", fmts:["Policy","Parli","Congress","World Schools","Speech"], act:37, t:2, seen:"2026" },
  { n:"Saint Joseph Notre Dame High School", st:"CA", fmts:["Policy","Parli"], act:36, t:3, seen:"2026" },
  { n:"La Canada High School", st:"CA", fmts:["Congress","World Schools","Big Questions","Speech"], act:36, t:3, seen:"2026" },
  { n:"Clovis North High School", st:"CA", fmts:["Policy","LD","Congress","World Schools","Speech"], act:36, t:3, seen:"2026" },
  { n:"Chaminade High School", st:"CA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:35, t:3, seen:"2026" },
  { n:"Homestead HS", st:"CA", fmts:["Policy","Parli","Congress","World Schools","Big Questions","Speech"], act:33, t:4, seen:"2026" },
  { n:"Castro Valley High School", st:"CA", fmts:["Congress","World Schools","Big Questions","Speech"], act:33, t:3, seen:"2026" },
  { n:"Analy High School", st:"CA", fmts:["Policy","Parli"], act:33, t:4, seen:"2026" },
  { n:"Rowland Hall", st:"CA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:33, t:3, seen:"2026" },
  { n:"Foothill High School", st:"CA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:33, t:2, seen:"2026" },
  { n:"North Hollywood High School", st:"CA", fmts:["Congress","World Schools","Big Questions","Speech"], act:33, t:2, seen:"2026" },
  { n:"American Canyon High School", st:"CA", fmts:["Policy","Parli"], act:32, t:3, seen:"2026" },
  { n:"Bishop Amat Memorial High School", st:"CA", fmts:["Speech"], act:31, t:4, seen:"2027" },
  { n:"Northwood High School", st:"CA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:31, t:2, seen:"2026" },
  { n:"Granada High School", st:"CA", fmts:["Speech"], act:31, t:2, seen:"2026" },
  { n:"Santa Rosa High School", st:"CA", fmts:["Policy","Parli"], act:30, t:2, seen:"2026" },
  { n:"Palo Verde High School", st:"CA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:30, t:2, seen:"2026" },
  { n:"Windemere Ranch Middle School", st:"CA", fmts:["Parli"], act:29, t:1, seen:"2025" },
  { n:"San Francisco Day School", st:"CA", act:29, t:2, seen:"2026" },
  { n:"Rise Academy", st:"CA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:29, t:3, seen:"2026" },
  { n:"Brentwood School", st:"CA", fmts:["Congress","World Schools","Big Questions","Speech"], act:29, t:2, seen:"2026" },
  { n:"California High School", st:"CA", fmts:["Congress","World Schools","Big Questions","Speech"], act:29, t:2, seen:"2026" },
  { n:"Benicia High School", st:"CA", fmts:["Policy","Parli"], act:29, t:5, seen:"2026" },
  { n:"Stockdale High School", st:"CA", fmts:["Policy","LD","Congress","World Schools","Speech"], act:29, t:3, seen:"2026" },
  { n:"Sage Hill School", st:"CA", fmts:["Policy","LD","Congress","World Schools","Speech"], act:29, t:3, seen:"2026" },
  { n:"Blach Intermediate School", st:"CA", fmts:["Congress","World Schools","Big Questions","Speech"], act:27, t:3, seen:"2026" },
  { n:"New Roads School", st:"CA", act:27, t:2, seen:"2026" },
  { n:"Capitol Debate", st:"CA", fmts:["Congress","World Schools","Big Questions","Speech"], act:27, t:1, seen:"2026" },
  { n:"Diamond Bar High School", st:"CA", fmts:["Policy","Parli","Congress","World Schools","Speech"], act:26, t:4, seen:"2026" },
  { n:"Russell Middle school", st:"CA", act:26, t:1, seen:"2025" },
  { n:"Crescenta Valley High School", st:"CA", fmts:["Congress"], act:25, t:2, seen:"2025" },
  { n:"Marin Academy", st:"CA", fmts:["Congress","World Schools","Big Questions","Speech"], act:25, t:1, seen:"2026" },
  { n:"Newport High School", st:"CA", fmts:["Congress","World Schools","Big Questions","Speech"], act:25, t:1, seen:"2026" },
  { n:"Thousand Oaks High School", st:"CA", fmts:["Congress","World Schools","Big Questions","Speech"], act:24, t:4, seen:"2026" },
  { n:"West Covina High School", st:"CA", fmts:["Policy","LD","Speech"], act:24, t:2, seen:"2026" },
  { n:"Dublin High School", st:"CA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:24, t:2, seen:"2026" },
  { n:"Collegiate School", st:"CA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:23, t:3, seen:"2026" },
  { n:"Pinole Valley High School", st:"CA", act:23, t:1, seen:"2026" },
  { n:"The King's Academy", st:"CA", fmts:["Congress","World Schools","Big Questions","Speech"], act:23, t:2, seen:"2026" },
  { n:"Chino Hills Independent", st:"CA", fmts:["Congress","Speech"], act:23, t:2, seen:"2025" },
  { n:"La Costa Canyon High School", st:"CA", act:21, t:2, seen:"2026" },
  { n:"Fremont High School", st:"CA", fmts:["Policy","Parli","Congress","World Schools","Speech"], act:21, t:1, seen:"2026" },
  { n:"Egan Junior High School", st:"CA", fmts:["Congress","World Schools","Big Questions","Speech"], act:19, t:2, seen:"2026" },
  { n:"Innovation Academy", st:"CA", fmts:["Policy","LD","Speech"], act:19, t:2, seen:"2026" },
  { n:"Valencia High School", st:"CA", fmts:["Policy","LD","Congress","World Schools","Speech"], act:19, t:2, seen:"2026" },
  { n:"Culver City High School", st:"CA", act:18, t:1, seen:"2026" },
  { n:"Sierra Canyon School", st:"CA", act:18, t:1, seen:"2026" },
  { n:"Silver Creek High School", st:"CA", fmts:["Policy","Parli","Congress","World Schools","Big Questions","Speech"], act:17, t:2, seen:"2026" },
  { n:"New West Charter School", st:"CA", fmts:["Policy","LD","Congress","World Schools","Speech"], act:17, t:2, seen:"2026" },
  { n:"Sequoia High School", st:"CA", act:17, t:2, seen:"2025" },
  { n:"Maranatha High School", st:"CA", act:17, t:1, seen:"2026" },
  { n:"East Bakersfield High School", st:"CA", act:17, t:1, seen:"2026" },
  { n:"San Pedro High School", st:"CA", fmts:["Policy","Parli","Congress","World Schools","Speech"], act:16, t:2, seen:"2027" },
  { n:"Arcadia High School", st:"CA", fmts:["Policy","LD","Congress","World Schools","Speech"], act:16, t:2, seen:"2026" },
  { n:"Westview High School", st:"CA", fmts:["Speech"], act:16, t:2, seen:"2025" },
  { n:"Oxford Academy", st:"CA", fmts:["Speech"], act:16, t:2, seen:"2025" },
  { n:"Independence HS", st:"CA", act:16, t:1, seen:"2026" },
  { n:"Foothill Country Day School", st:"CA", fmts:["Congress"], act:16, t:1, seen:"2025" },
  { n:"Parliamentary Debate at Berkeley", st:"CA", act:16, t:2, seen:"2026" },
  { n:"Richland High School", st:"CA", act:15, t:1, seen:"2025" },
  { n:"Alliance Academy", st:"CA", fmts:["Congress","World Schools","Big Questions","Speech"], act:15, t:1, seen:"2026" },
  { n:"Parker School", st:"CA", act:15, t:1, seen:"2026" },
  { n:"Peninsula Academy Debate", st:"CA", fmts:["Speech"], act:15, t:1, seen:"2025" },
  { n:"Segerstrom High School", st:"CA", fmts:["Policy","LD","Speech"], act:14, t:1, seen:"2026" },
  { n:"Middle College High School", st:"CA", fmts:["Policy","LD","Speech"], act:14, t:1, seen:"2026" },
  { n:"Wilcox High School", st:"CA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:14, t:2, seen:"2026" },
  { n:"Francis Parker School", st:"CA", fmts:["Policy","Parli","Congress","World Schools","Speech"], act:14, t:2, seen:"2026" },
  { n:"Western High School", st:"CA", fmts:["Policy","LD","Speech"], act:14, t:1, seen:"2026" },
  { n:"Mountain House High School", st:"CA", fmts:["Policy","LD","Congress","World Schools","Speech"], act:14, t:1, seen:"2026" },
  { n:"Branham High School", st:"CA", fmts:["Speech"], act:14, t:2, seen:"2025" },
  { n:"Berkeley Independent", st:"CA", fmts:["Congress","World Schools","Big Questions","Speech"], act:14, t:2, seen:"2026" },
  { n:"Mt.Carmel High School", st:"CA", fmts:["Congress","World Schools","Big Questions","Speech"], act:13, t:1, seen:"2026" },
  { n:"Columbus HS", st:"CA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:12, t:2, seen:"2026" },
  { n:"Santa Ana High School", st:"CA", fmts:["Policy","LD","Speech"], act:12, t:1, seen:"2026" },
  { n:"Bakersfield High School", st:"CA", act:12, t:1, seen:"2026" },
  { n:"BASIS Independent Fremont(HS)", st:"CA", act:12, t:1, seen:"2026" },
  { n:"San Domenico Upper School", st:"CA", fmts:["Congress","World Schools","Big Questions","Speech"], act:11, t:1, seen:"2026" },
  { n:"Emery High School", st:"CA", fmts:["Congress","World Schools","Big Questions","Speech"], act:11, t:1, seen:"2026" },
  { n:"Frazer School", st:"CA", fmts:["Congress","World Schools","Big Questions","Speech"], act:11, t:1, seen:"2026" },
  { n:"Timothy Christian", st:"CA", fmts:["Policy","LD","Speech"], act:10, t:1, seen:"2026" },
  { n:"Lower Lake High School", st:"CA", act:10, t:1, seen:"2026" },
  { n:"Middle College High", st:"CA", fmts:["Congress"], act:10, t:1, seen:"2025" },
  { n:"Pomona Catholic", st:"CA", fmts:["Congress"], act:10, t:1, seen:"2025" },
  { n:"Oak Grove HS", st:"CA", fmts:["Policy","LD","Speech"], act:9, t:1, seen:"2026" },
  { n:"Branson School", st:"CA", fmts:["Congress","World Schools","Big Questions","Speech"], act:9, t:1, seen:"2026" },
  { n:"Valley View High School", st:"CA", fmts:["Congress"], act:9, t:1, seen:"2025" },
  { n:"The Meadows School", st:"CA", fmts:["Congress","World Schools","Big Questions","Speech"], act:8, t:1, seen:"2026" },
  { n:"Eastside High School", st:"CA", act:8, t:1, seen:"2025" },
  { n:"Burlingame High School", st:"CA", act:7, t:1, seen:"2025" },
  { n:"El Camino College", st:"CA", act:3, t:1, seen:"2021" },
  { n:"Irvington High School", st:"CA" },
  { n:"Westlake High School", st:"CA" },
  { n:"Gunn High School", st:"CA" },
  { n:"Peninsula Academy", st:"CA" },
  { n:"Monte Vista HS", st:"CA" },
  { n:"Fort Collins High School", st:"CO", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:34, t:2, seen:"2026" },
  { n:"Cherokee Trail High School", st:"CO", fmts:["Policy","LD","Speech"], act:21, t:1, seen:"2026" },
  { n:"Fossil Ridge HS", st:"CO", fmts:["Policy","LD","Speech"], act:12, t:1, seen:"2026" },
  { n:"Academy of Information Technology and Engineering", st:"CT", act:58, t:6, seen:"2026" },
  { n:"St. Luke's School", st:"CT", fmts:["Policy","LD","PF","Congress","World Schools","Big Questions","Speech"], act:49, t:3, seen:"2026" },
  { n:"Franklin Academy", st:"CT", fmts:["Policy","LD","PF","Congress","World Schools","Big Questions","Speech"], act:20, t:3, seen:"2026" },
  { n:"St. Paul Central HS", st:"CT", fmts:["Policy","LD","PF","Congress","World Schools"], act:17, t:1, seen:"2025" },
  { n:"Amity Regional High School", st:"CT", act:12, t:2, seen:"2026" },
  { n:"American Debate League", st:"CT", fmts:["Policy","LD","Speech"], act:8, t:1, seen:"2026" },
  { n:"Windsor High School", st:"CT" },
  { n:"Georgetown Day School", st:"DC", fmts:["Policy","LD","PF","Congress","World Schools","Speech"], act:43, t:3, seen:"2026" },
  { n:"School Without Walls High School", st:"DC", fmts:["Policy","LD","Congress","World Schools","Speech"], act:32, t:3, seen:"2026" },
  { n:"Maret School", st:"DC", fmts:["Policy","LD","Congress","World Schools","Speech"], act:13, t:1, seen:"2026" },
  { n:"Heritage High Speech and Debate Club", st:"FL", fmts:["Policy","LD","Parli","Congress","World Schools","Speech"], act:325, t:6, seen:"2026" },
  { n:"Trinity Preparatory School", st:"FL", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:64, t:3, seen:"2026" },
  { n:"Gulf Breeze High School", st:"FL", act:53, t:1, seen:"2025" },
  { n:"Robinson High School", st:"FL", fmts:["Policy","LD","Congress","World Schools","Speech"], act:52, t:2, seen:"2026" },
  { n:"Glen Ridge Debate Club", st:"FL", act:41, t:4, seen:"2026" },
  { n:"Fort Walton Beach High School", st:"FL", fmts:["Policy","LD","Speech"], act:33, t:2, seen:"2026" },
  { n:"Carrollwood Day School", st:"FL", fmts:["Policy","LD","Speech"], act:30, t:2, seen:"2026" },
  { n:"Stoneman Douglas High School", st:"FL", fmts:["Policy","LD","Speech"], act:28, t:1, seen:"2026" },
  { n:"Lake Mary High School", st:"FL", fmts:["Policy","LD","Speech"], act:28, t:1, seen:"2026" },
  { n:"Newsome High School", st:"FL", fmts:["Policy","LD","Congress","World Schools","Speech"], act:28, t:2, seen:"2026" },
  { n:"Fort Lauderdale High School", st:"FL", fmts:["Policy","LD","Speech"], act:25, t:1, seen:"2026" },
  { n:"DHS Independent", st:"FL", fmts:["Policy","Parli","Congress","World Schools","Speech"], act:24, t:3, seen:"2026" },
  { n:"John I Leonard High School", st:"FL", fmts:["Policy","LD","Speech"], act:23, t:1, seen:"2026" },
  { n:"Carrollton School of the Sacred Heart", st:"FL", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:23, t:2, seen:"2026" },
  { n:"Palm Beach Independent", st:"FL", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:20, t:2, seen:"2026" },
  { n:"West Broward High School", st:"FL", fmts:["Policy","LD","Congress","World Schools","Speech"], act:17, t:2, seen:"2026" },
  { n:"Gulliver Prep", st:"FL", act:17, t:1, seen:"2025" },
  { n:"Olympic Heights Community High School", st:"FL", fmts:["Policy","LD","Speech"], act:16, t:1, seen:"2026" },
  { n:"Miami Country Day School", st:"FL", fmts:["Policy","LD","Speech"], act:15, t:1, seen:"2026" },
  { n:"Lake Brantley High School", st:"FL", fmts:["Policy","LD","Congress","World Schools","Speech"], act:14, t:2, seen:"2026" },
  { n:"Cypress Creek HS", st:"FL", fmts:["Policy","LD","Speech"], act:13, t:1, seen:"2026" },
  { n:"Coral Glades High", st:"FL", fmts:["Policy","LD","Speech"], act:12, t:1, seen:"2026" },
  { n:"Our Lady of Lourdes Academy", st:"FL", fmts:["Policy","LD","Speech"], act:10, t:1, seen:"2026" },
  { n:"Oxbridge Academy", st:"FL", fmts:["Policy","LD","Speech"], act:9, t:1, seen:"2026" },
  { n:"Cooper City High School", st:"FL", fmts:["Policy","LD","Speech"], act:9, t:1, seen:"2026" },
  { n:"Heritage High Club", st:"FL" },
  { n:"Athens Debate", st:"GA", fmts:["Congress","World Schools","Big Questions","Speech"], act:343, t:2, seen:"2026" },
  { n:"National Debate Club (NDC)", st:"GA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:48, t:3, seen:"2026" },
  { n:"Omega Speech and Debate", st:"GA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:43, t:2, seen:"2026" },
  { n:"Johns Creek High School", st:"GA", fmts:["Policy","LD","PF","Congress","World Schools","Speech"], act:42, t:3, seen:"2026" },
  { n:"Chattahoochee High School", st:"GA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:32, t:2, seen:"2026" },
  { n:"Valdosta High School", st:"GA", act:17, t:1, seen:"2025" },
  { n:"South Forsyth High School", st:"GA", fmts:["Congress","World Schools","Big Questions","Speech"], act:9, t:1, seen:"2026" },
  { n:"Nest Independent", st:"IA", act:54, t:4, seen:"2026" },
  { n:"Pioneer Speech and Debate", st:"IA", fmts:["Policy","LD","Speech"], act:9, t:1, seen:"2026" },
  { n:"West Boca Raton HS", st:"ID", fmts:["Policy","LD","Congress","World Schools","Speech"], act:30, t:2, seen:"2026" },
  { n:"White Pine STEM Academy", st:"ID", fmts:["Speech"], act:11, t:1, seen:"2025" },
  { n:"New Trier High School", st:"IL", fmts:["Policy","LD","PF","Congress","World Schools","Speech"], act:51, t:3, seen:"2026" },
  { n:"Adlai E. Stevenson High School", st:"IL", fmts:["Policy","LD","Congress","World Schools","Speech"], act:27, t:2, seen:"2026" },
  { n:"William Fremd High School", st:"IL", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:27, t:2, seen:"2026" },
  { n:"The Avery Coonley School", st:"IL", fmts:["Policy","LD","Speech"], act:25, t:1, seen:"2026" },
  { n:"Brother Rice High School", st:"IL", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:17, t:2, seen:"2026" },
  { n:"Meridian High School", st:"IL", act:16, t:1, seen:"2025" },
  { n:"Homewood-Flossmoor High School", st:"IL", act:13, t:1, seen:"2025" },
  { n:"Jesuit College Prep", st:"IL", act:13, t:1, seen:"2026" },
  { n:"Illini Forensics", st:"IL", act:3, t:1, seen:"2021" },
  { n:"NAVI Debate", st:"IN", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:80, t:3, seen:"2026" },
  { n:"CR North High School", st:"IN", fmts:["Policy","LD","Congress","World Schools","Speech"], act:57, t:3, seen:"2026" },
  { n:"Claremont", st:"KY", fmts:["Policy","LD","Congress","World Schools","Speech"], act:171, t:3, seen:"2026" },
  { n:"McDowell HS", st:"KY", fmts:["Policy","LD","Congress","World Schools","Speech"], act:54, t:2, seen:"2026" },
  { n:"Bellevue High School", st:"KY", fmts:["Policy","LD","Congress","World Schools","Speech"], act:52, t:2, seen:"2026" },
  { n:"Westridge School", st:"KY", fmts:["Policy","LD","Congress","World Schools","Speech"], act:46, t:2, seen:"2026" },
  { n:"Fairview HS", st:"KY", fmts:["Policy","LD","Congress","World Schools","Speech"], act:39, t:2, seen:"2026" },
  { n:"Xavier High School", st:"KY", fmts:["Policy","LD","Congress","World Schools","Speech"], act:18, t:2, seen:"2026" },
  { n:"Madison Central HS", st:"KY", fmts:["Policy","LD","Speech"], act:16, t:1, seen:"2026" },
  { n:"University School", st:"KY", fmts:["Policy","LD","Congress","World Schools","Speech"], act:14, t:1, seen:"2026" },
  { n:"Little Rock Central", st:"LA", fmts:["Policy","LD","PF","Congress","World Schools","Speech"], act:112, t:4, seen:"2026" },
  { n:"Isidore Newman School", st:"LA", fmts:["Policy","LD","PF","Congress","World Schools","Big Questions","Speech"], act:82, t:5, seen:"2026" },
  { n:"St. Andrew's Episcopal School", st:"LA", fmts:["Policy","LD","Speech"], act:63, t:2, seen:"2026" },
  { n:"St. Thomas HS", st:"LA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:32, t:4, seen:"2026" },
  { n:"Caddo Magnet High School", st:"LA", act:31, t:1, seen:"2025" },
  { n:"The Willow School", st:"LA", act:30, t:1, seen:"2025" },
  { n:"Mount Carmel Academy", st:"LA", act:24, t:1, seen:"2025" },
  { n:"Rock Hill HS", st:"LA", act:20, t:1, seen:"2025" },
  { n:"St. Augustine High School", st:"LA", act:20, t:1, seen:"2025" },
  { n:"Zachary High School", st:"LA", act:20, t:1, seen:"2025" },
  { n:"David Thibodaux STEM Magnet Academy", st:"LA", act:19, t:1, seen:"2025" },
  { n:"Teurlings Catholic High School", st:"LA", act:17, t:1, seen:"2025" },
  { n:"Patrick F. Taylor Science and Technology Academy", st:"LA", fmts:["Policy","LD","Speech"], act:16, t:2, seen:"2026" },
  { n:"Pope John Paul II Catholic High School", st:"LA", act:15, t:1, seen:"2025" },
  { n:"Fisher Middle High School", st:"LA", act:15, t:1, seen:"2025" },
  { n:"St Martin's Episcopal School", st:"LA", act:14, t:1, seen:"2025" },
  { n:"Destrehan High School", st:"LA", act:12, t:1, seen:"2025" },
  { n:"Ascension Episcopal School", st:"LA", act:9, t:1, seen:"2025" },
  { n:"The Dunham School", st:"LA", act:9, t:1, seen:"2025" },
  { n:"Tulane University Debate Team", st:"LA", act:2, t:1, seen:"2021" },
  { n:"Sophie B. Wright Institute Of Academic Excellence school LA", st:"LA" },
  { n:"Horace Mann Parliamentary Debate", st:"MA", fmts:["LD","PF","Parli"], act:186, t:16, seen:"2026" },
  { n:"Brooks Debate Institute", st:"MA", fmts:["Policy","Parli","Congress","World Schools","Speech"], act:148, t:7, seen:"2026" },
  { n:"Newton South High School", st:"MA", fmts:["Policy","LD","Congress","World Schools","Speech"], act:125, t:2, seen:"2026" },
  { n:"Acton-Boxborough Regional High School", st:"MA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:89, t:3, seen:"2026" },
  { n:"Horace Mann School", st:"MA", fmts:["Policy","LD","Congress","World Schools","Speech"], act:52, t:3, seen:"2026" },
  { n:"Randolph High School", st:"MA", fmts:["Policy","LD","Speech"], act:40, t:1, seen:"2026" },
  { n:"Westborough High School", st:"MA", fmts:["Policy","LD","Speech"], act:36, t:1, seen:"2026" },
  { n:"Lincoln-Sudbury Regional HS", st:"MA", fmts:["Policy","LD","Congress","World Schools","Speech"], act:35, t:2, seen:"2026" },
  { n:"Concord Carlisle High School", st:"MA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:27, t:3, seen:"2026" },
  { n:"The Hill School", st:"MA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:24, t:2, seen:"2026" },
  { n:"Catholic Memorial School", st:"MA", fmts:["Policy","LD","Speech"], act:22, t:1, seen:"2026" },
  { n:"GO DEBATE ACADEMY", st:"MA", fmts:["Policy","LD","Speech"], act:22, t:1, seen:"2026" },
  { n:"Winchester High School", st:"MA", fmts:["Policy","LD","Speech"], act:20, t:2, seen:"2026" },
  { n:"Walpole High School", st:"MA", fmts:["Policy","LD","Speech"], act:20, t:1, seen:"2026" },
  { n:"LAMP HS", st:"MA", fmts:["Policy","LD","Speech"], act:19, t:1, seen:"2026" },
  { n:"Boston Latin School", st:"MA", fmts:["Policy","LD","Congress","World Schools","Speech"], act:19, t:2, seen:"2026" },
  { n:"St. Michael's School", st:"MA", fmts:["Policy","LD","Speech"], act:13, t:1, seen:"2026" },
  { n:"Somerville High School", st:"MA", fmts:["Policy","LD","Speech"], act:13, t:1, seen:"2026" },
  { n:"Natick High School", st:"MA", fmts:["Policy","LD","Speech"], act:13, t:1, seen:"2026" },
  { n:"Brookline High School", st:"MA", fmts:["Policy","LD","Speech"], act:12, t:1, seen:"2026" },
  { n:"Saint Joseph School", st:"MA", fmts:["Policy","LD","Speech"], act:10, t:1, seen:"2026" },
  { n:"Hanover High School", st:"MA", fmts:["Policy","LD","Speech"], act:10, t:1, seen:"2026" },
  { n:"New England Innovation Academy", st:"MA", fmts:["Policy","LD","Speech"], act:9, t:1, seen:"2026" },
  { n:"Village Academy High School", st:"MA", fmts:["Congress"], act:9, t:1, seen:"2025" },
  { n:"Saint George School", st:"MA", fmts:["Policy","LD","Speech"], act:8, t:1, seen:"2026" },
  { n:"Saint Mary's Hall", st:"MA", fmts:["Policy","LD","Speech"], act:8, t:1, seen:"2026" },
  { n:"Suffolk University Debate", st:"MA", act:6, t:1, seen:"2025" },
  { n:"Brooks Institute", st:"MA" },
  { n:"GO ACADEMY", st:"MA" },
  { n:"Winston Churchill HS", st:"MD", fmts:["Policy","LD","Congress","World Schools","Speech"], act:45, t:3, seen:"2026" },
  { n:"Baltimore City College", st:"MD", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:26, t:3, seen:"2026" },
  { n:"Sandy Spring Friends School", st:"MD", fmts:["Policy","LD","Congress","World Schools","Speech"], act:16, t:2, seen:"2026" },
  { n:"Kent School", st:"MD", fmts:["Policy","LD","Speech"], act:14, t:1, seen:"2026" },
  { n:"Georgetown Preparatory School", st:"MD", fmts:["Policy","LD","Speech"], act:10, t:1, seen:"2026" },
  { n:"Math and Science Academy", st:"ME", fmts:["Policy","LD","PF","Congress","World Schools","Big Questions","Speech"], act:52, t:3, seen:"2026" },
  { n:"Wylie E. Groves HS", st:"MI", fmts:["Policy","LD","PF","Congress","World Schools","Speech"], act:18, t:2, seen:"2026" },
  { n:"Okemos High School", st:"MI", fmts:["Policy","LD","Congress","World Schools","Speech"], act:16, t:2, seen:"2026" },
  { n:"Evergreen Academy", st:"MI", fmts:["Policy","Parli","Congress","World Schools","Speech"], act:12, t:1, seen:"2026" },
  { n:"Lexington HS", st:"MN", fmts:["Policy","LD","PF","Congress","World Schools","Speech"], act:95, t:3, seen:"2026" },
  { n:"Eagan High School", st:"MN", fmts:["Policy","LD","PF","Congress","World Schools","Speech"], act:92, t:3, seen:"2026" },
  { n:"Edina High School", st:"MN", fmts:["Policy","LD","PF","Congress","World Schools","Speech"], act:83, t:3, seen:"2026" },
  { n:"Lakeville North High School", st:"MN", fmts:["Policy","LD","PF","Congress","World Schools","Speech"], act:79, t:2, seen:"2026" },
  { n:"The Blake School", st:"MN", fmts:["Policy","LD","PF","Congress","World Schools","Speech"], act:79, t:3, seen:"2026" },
  { n:"Lumos", st:"MN", fmts:["Policy","LD","Speech"], act:75, t:1, seen:"2026" },
  { n:"Eden Prairie High School", st:"MN", fmts:["Policy","LD","PF","Congress","World Schools","Big Questions","Speech"], act:70, t:5, seen:"2026" },
  { n:"Apple Valley High School", st:"MN", fmts:["Policy","LD","PF","Congress","World Schools","Speech"], act:38, t:2, seen:"2026" },
  { n:"Mounds Park Academy", st:"MN", fmts:["Policy","LD","Speech"], act:25, t:1, seen:"2026" },
  { n:"Dassel Cokato High School", st:"MN", fmts:["Policy","LD","Speech"], act:21, t:1, seen:"2026" },
  { n:"Minneapolis South HS", st:"MN", fmts:["Policy","LD","PF","Congress","World Schools","Speech"], act:20, t:2, seen:"2026" },
  { n:"Lakeville South High School", st:"MN", fmts:["Policy","LD","PF","Congress","World Schools"], act:20, t:1, seen:"2025" },
  { n:"Minnetonka High School", st:"MN", fmts:["Policy","LD","PF","Congress","World Schools"], act:19, t:1, seen:"2025" },
  { n:"Global Speech and Debate Academy", st:"MN", fmts:["Congress","World Schools","Big Questions","Speech"], act:19, t:1, seen:"2026" },
  { n:"East Ridge High School", st:"MN", fmts:["Policy","LD","PF","Congress","World Schools","Big Questions","Speech"], act:16, t:2, seen:"2026" },
  { n:"Denfeld High School", st:"MN", fmts:["Policy","LD","Speech"], act:11, t:1, seen:"2026" },
  { n:"Two Rivers High School", st:"MN", fmts:["Policy","LD","PF","Congress","World Schools"], act:11, t:1, seen:"2025" },
  { n:"St. Francis HS", st:"MN", fmts:["Policy","LD","PF","Congress","World Schools"], act:10, t:1, seen:"2025" },
  { n:"Irondale High School", st:"MN", fmts:["Policy","LD","Speech"], act:9, t:1, seen:"2026" },
  { n:"Tartan HS", st:"MN", fmts:["Policy","LD","PF","Congress","World Schools"], act:9, t:1, seen:"2025" },
  { n:"Macalester College", st:"MN", act:6, t:1, seen:"2025" },
  { n:"Global Academy", st:"MN" },
  { n:"Academy of Higher Learning", st:"MO", fmts:["Congress","World Schools","Big Questions","Speech"], act:60, t:4, seen:"2026" },
  { n:"Chaminade College Prep", st:"MO", fmts:["Policy","LD","Speech"], act:17, t:1, seen:"2026" },
  { n:"Truman High School", st:"MO", fmts:["Policy","LD","Congress","World Schools","Speech"], act:10, t:1, seen:"2026" },
  { n:"Murrah High School", st:"MS", act:19, t:1, seen:"2025" },
  { n:"McCallum HS", st:"MS", fmts:["Policy","LD","Speech"], act:16, t:1, seen:"2026" },
  { n:"Cary Academy", st:"NC", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:180, t:11, seen:"2026" },
  { n:"Marvin Ridge High School", st:"NC", fmts:["Congress","World Schools","Big Questions","Speech"], act:25, t:1, seen:"2026" },
  { n:"Asheville High School", st:"NC", fmts:["Policy","LD","Speech"], act:15, t:1, seen:"2026" },
  { n:"Lincoln East High School", st:"NE", fmts:["Policy","LD","Congress","World Schools","Speech"], act:15, t:1, seen:"2026" },
  { n:"Lincoln Northwest High School", st:"NE", fmts:["Congress","World Schools","Big Questions","Speech"], act:13, t:1, seen:"2026" },
  { n:"BOW Debate", st:"NH", act:30, t:5, seen:"2026" },
  { n:"Portsmouth High School", st:"NH", fmts:["Policy","LD","Speech"], act:15, t:1, seen:"2026" },
  { n:"Bergen Debate Club", st:"NJ", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:159, t:4, seen:"2026" },
  { n:"Bridgewater Raritan", st:"NJ", fmts:["Policy","LD","Congress","World Schools","Speech"], act:87, t:2, seen:"2026" },
  { n:"Delbarton School", st:"NJ", fmts:["Policy","LD","PF","Congress","World Schools","Big Questions","Speech"], act:76, t:5, seen:"2026" },
  { n:"Barringer High School", st:"NJ", fmts:["Policy","LD","Congress","World Schools","Speech"], act:45, t:2, seen:"2026" },
  { n:"Cherry Hill High School East", st:"NJ", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:30, t:3, seen:"2026" },
  { n:"UCVTS Independent", st:"NJ", fmts:["Policy","LD","Speech"], act:30, t:1, seen:"2026" },
  { n:"Nova Institute", st:"NJ", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:22, t:2, seen:"2026" },
  { n:"Woodrow Wilson HS", st:"NJ", fmts:["Policy","LD","Speech"], act:19, t:1, seen:"2026" },
  { n:"Princeton Day School", st:"NJ", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:18, t:2, seen:"2026" },
  { n:"Arts High School", st:"NJ", fmts:["Policy","LD","Speech"], act:16, t:1, seen:"2026" },
  { n:"Monroe Township High School", st:"NJ", fmts:["Policy","LD","Congress","World Schools","Speech"], act:16, t:2, seen:"2026" },
  { n:"Elizabeth High School", st:"NJ", fmts:["Policy","LD","Speech"], act:16, t:1, seen:"2026" },
  { n:"Long Branch High School", st:"NJ", fmts:["Policy","LD","Speech"], act:13, t:1, seen:"2026" },
  { n:"The Pingry School", st:"NJ", fmts:["Policy","LD","Speech"], act:9, t:1, seen:"2026" },
  { n:"Dwight Englewood School", st:"NJ", fmts:["Speech"], act:9, t:1, seen:"2025" },
  { n:"Albuquerque Academy", st:"NM", fmts:["Congress","World Schools","Big Questions","Speech"], act:59, t:3, seen:"2026" },
  { n:"East Mountain High School", st:"NM", fmts:["Policy","LD","Congress","World Schools","Speech"], act:20, t:2, seen:"2026" },
  { n:"Santa Fe Prep", st:"NM", act:11, t:1, seen:"2025" },
  { n:"Midtown High School", st:"NV", act:61, t:2, seen:"2026" },
  { n:"Lambert High School", st:"NV", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:54, t:4, seen:"2026" },
  { n:"Mountain Brook High School", st:"NV", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:54, t:3, seen:"2026" },
  { n:"Farmington High School", st:"NV", fmts:["Policy","LD","PF","Congress","World Schools","Big Questions","Speech"], act:46, t:4, seen:"2026" },
  { n:"Desert Vista High School", st:"NV", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:44, t:3, seen:"2026" },
  { n:"The Village High School", st:"NV", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:39, t:3, seen:"2026" },
  { n:"Edgewood High School", st:"NV", fmts:["Policy","LD","Speech"], act:34, t:2, seen:"2026" },
  { n:"Capital High School", st:"NV", fmts:["Congress","World Schools","Big Questions","Speech"], act:31, t:1, seen:"2026" },
  { n:"Mount Vernon High School", st:"NV", fmts:["Policy","LD","PF","Congress","World Schools","Big Questions","Speech"], act:30, t:3, seen:"2026" },
  { n:"Cypress Ranch High School", st:"NV", fmts:["Policy","LD","Speech"], act:29, t:1, seen:"2026" },
  { n:"Pine Creek High School", st:"NV", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:26, t:2, seen:"2026" },
  { n:"Melissa High School", st:"NV", fmts:["Policy","LD","Speech"], act:23, t:1, seen:"2026" },
  { n:"Galena High School", st:"NV", act:23, t:1, seen:"2026" },
  { n:"Cypress Falls High School", st:"NV", fmts:["Policy","LD","Speech"], act:20, t:1, seen:"2026" },
  { n:"Elko High School", st:"NV", act:19, t:1, seen:"2026" },
  { n:"Rye High School", st:"NV", fmts:["Congress","World Schools","Big Questions","Speech"], act:18, t:1, seen:"2026" },
  { n:"Wasatch High School", st:"NV", act:16, t:1, seen:"2026" },
  { n:"Pinecrest High School", st:"NV", fmts:["Policy","LD","Speech"], act:16, t:1, seen:"2026" },
  { n:"Tompkins High School", st:"NV", fmts:["Policy","LD","Speech"], act:12, t:1, seen:"2026" },
  { n:"Damonte Ranch High School", st:"NV", act:12, t:1, seen:"2026" },
  { n:"Grapevine High School", st:"NV", fmts:["Policy","LD","Speech"], act:10, t:1, seen:"2026" },
  { n:"Coral Academy of Science Las Vegas", st:"NV", act:10, t:1, seen:"2026" },
  { n:"Littleton High School", st:"NV", fmts:["Congress","World Schools","Big Questions","Speech"], act:9, t:1, seen:"2026" },
  { n:"Lubbock High School", st:"NV", fmts:["Policy","LD","Speech"], act:7, t:1, seen:"2026" },
  { n:"Brooklyn Tech", st:"NY", fmts:["Speech"], act:492, t:21, seen:"2026" },
  { n:"The Dalton School", st:"NY", fmts:["LD","PF","Parli"], act:320, t:19, seen:"2026" },
  { n:"Horace Greeley HS", st:"NY", fmts:["Policy","LD","PF","Congress","World Schools","Big Questions","Speech"], act:173, t:8, seen:"2026" },
  { n:"Friends Seminary", st:"NY", fmts:["Parli"], act:140, t:10, seen:"2026" },
  { n:"Syosset High School", st:"NY", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:115, t:4, seen:"2026" },
  { n:"Stuyvesant High School", st:"NY", fmts:["Policy","LD","Congress","World Schools","Speech"], act:112, t:6, seen:"2026" },
  { n:"Trinity School", st:"NY", fmts:["Parli"], act:110, t:11, seen:"2026" },
  { n:"Blind Brook Debate Team", st:"NY", fmts:["Parli"], act:94, t:7, seen:"2026" },
  { n:"CT Independent", st:"NY", fmts:["Parli"], act:93, t:12, seen:"2026" },
  { n:"Saint Ann's School", st:"NY", fmts:["Parli"], act:78, t:6, seen:"2026" },
  { n:"Manhattan Independent", st:"NY", fmts:["LD","PF","Parli"], act:74, t:10, seen:"2026" },
  { n:"Nova 42 Academy", st:"NY", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:70, t:3, seen:"2026" },
  { n:"Regis High School", st:"NY", fmts:["Policy","LD","Speech"], act:68, t:1, seen:"2026" },
  { n:"Mamaroneck High School", st:"NY", fmts:["Policy","LD","PF","Congress","World Schools","Speech"], act:53, t:3, seen:"2026" },
  { n:"Scarsdale High School", st:"NY", fmts:["Policy","LD","Congress","World Schools","Speech"], act:50, t:3, seen:"2026" },
  { n:"Grace Church School", st:"NY", fmts:["Policy","LD","Speech"], act:43, t:5, seen:"2026" },
  { n:"Theodore Roosevelt High School", st:"NY", fmts:["Policy","LD","PF","Congress","World Schools","Speech"], act:41, t:2, seen:"2026" },
  { n:"Packer Collegiate Institute", st:"NY", fmts:["Policy","LD","Congress","World Schools","Speech"], act:27, t:2, seen:"2026" },
  { n:"Brooklyn Technical High School", st:"NY", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:27, t:2, seen:"2026" },
  { n:"Hackley School", st:"NY", act:26, t:2, seen:"2025" },
  { n:"Townsend Harris High School", st:"NY", fmts:["Policy","LD","Speech"], act:24, t:1, seen:"2026" },
  { n:"Frederick Douglass High School", st:"NY", act:22, t:1, seen:"2025" },
  { n:"Midwood High School", st:"NY", act:21, t:1, seen:"2025" },
  { n:"Riverdale Country School", st:"NY", fmts:["Policy","LD","Congress","World Schools","Speech"], act:20, t:2, seen:"2026" },
  { n:"The Wheatley School", st:"NY", fmts:["Policy","LD","Speech"], act:16, t:1, seen:"2026" },
  { n:"Fordham Preparatory School", st:"NY", fmts:["Policy","LD","Speech"], act:16, t:1, seen:"2026" },
  { n:"Molloy HS", st:"NY", fmts:["Policy","LD","Speech"], act:15, t:1, seen:"2026" },
  { n:"The Greene School", st:"NY", fmts:["Policy","LD","Congress","World Schools","Speech"], act:14, t:2, seen:"2026" },
  { n:"Avenues Independent", st:"NY", act:12, t:2, seen:"2026" },
  { n:"Loyola School", st:"NY", fmts:["Policy","LD","Congress","World Schools","Speech"], act:11, t:1, seen:"2026" },
  { n:"Stuyvesant Independent", st:"NY", act:11, t:1, seen:"2026" },
  { n:"The Masters School", st:"NY", fmts:["Policy","LD","Speech"], act:10, t:1, seen:"2026" },
  { n:"Newtown HS", st:"NY", fmts:["Policy","LD","Speech"], act:9, t:1, seen:"2026" },
  { n:"Hastings HS", st:"NY", fmts:["Policy","LD","Speech"], act:9, t:1, seen:"2026" },
  { n:"Long Island Independent", st:"NY", fmts:["Policy","LD","Speech"], act:9, t:1, seen:"2026" },
  { n:"Independent Quakers", st:"NY", act:9, t:1, seen:"2025" },
  { n:"Seven Bridges Middle School", st:"NY", fmts:["Policy","LD","Speech"], act:8, t:1, seen:"2026" },
  { n:"Francis Lewis HS", st:"NY", fmts:["Policy","LD","Speech"], act:8, t:1, seen:"2026" },
  { n:"Bayside High School", st:"NY", fmts:["Policy","LD","Speech"], act:8, t:1, seen:"2026" },
  { n:"Brooklyn Technical High School Parliamentary Debate Team", st:"NY" },
  { n:"Harrison", st:"OH", fmts:["Policy","LD","PF","Congress","World Schools","Big Questions","Speech"], act:84, t:6, seen:"2026" },
  { n:"Olentangy High School", st:"OH", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:27, t:3, seen:"2026" },
  { n:"Olentangy Orange High School", st:"OH", fmts:["Policy","LD","Congress","World Schools","Speech"], act:17, t:2, seen:"2026" },
  { n:"Woodlands Independent", st:"OH", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:16, t:2, seen:"2026" },
  { n:"Tuscarawas Valley High School", st:"OH", fmts:["Policy","LD","Congress","World Schools","Speech"], act:9, t:1, seen:"2026" },
  { n:"Highland Independent", st:"OH", act:9, t:1, seen:"2026" },
  { n:"Dublin High", st:"OH" },
  { n:"Mustang Speech and Debate", st:"OK", fmts:["Congress","World Schools","Big Questions","Speech"], act:112, t:3, seen:"2026" },
  { n:"Bixby High School", st:"OK", fmts:["Policy","LD","Speech"], act:27, t:1, seen:"2026" },
  { n:"Sequoyah School", st:"OK", fmts:["Policy","LD","Speech"], act:12, t:2, seen:"2026" },
  { n:"Summit HS", st:"OR", fmts:["Policy","LD","Congress","World Schools","Speech"], act:124, t:3, seen:"2026" },
  { n:"South Eugene High School", st:"OR", fmts:["Congress","World Schools","Big Questions","Speech"], act:22, t:3, seen:"2026" },
  { n:"Parkrose High School", st:"OR", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:16, t:2, seen:"2026" },
  { n:"Sam Barlow HS", st:"OR", fmts:["Policy","Parli","Congress","World Schools","Speech"], act:15, t:2, seen:"2026" },
  { n:"Ethos Academy", st:"OR", fmts:["Congress","World Schools","Big Questions","Speech"], act:13, t:1, seen:"2026" },
  { n:"Speech and Debate India", st:"PA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:100, t:4, seen:"2026" },
  { n:"Hunter College", st:"PA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:94, t:3, seen:"2026" },
  { n:"Harriton High School", st:"PA", act:64, t:6, seen:"2026" },
  { n:"Waring School", st:"PA", fmts:["Policy","LD","PF","Congress","World Schools","Speech"], act:45, t:4, seen:"2026" },
  { n:"Elkins High School", st:"PA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:24, t:3, seen:"2026" },
  { n:"Pennsbury High School", st:"PA", fmts:["Policy","LD","Congress","World Schools","Speech"], act:19, t:2, seen:"2026" },
  { n:"Our Lady of the Sacred Heart High School", st:"PA", fmts:["Policy","LD","Congress","World Schools","Speech"], act:15, t:1, seen:"2026" },
  { n:"Gwynedd Mercy Academy", st:"PA", fmts:["Policy","LD","Speech"], act:12, t:1, seen:"2026" },
  { n:"Germantown Academy", st:"PA", fmts:["Policy","LD","Speech"], act:12, t:1, seen:"2026" },
  { n:"Harrisburg High School", st:"PA", fmts:["Policy","LD","Congress","World Schools","Speech"], act:12, t:1, seen:"2026" },
  { n:"Shady Side Academy", st:"PA", fmts:["Policy","LD","Congress","World Schools","Speech"], act:11, t:1, seen:"2026" },
  { n:"Jenks High School", st:"RI", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:25, t:2, seen:"2026" },
  { n:"Rock Hill Independent", st:"SC", fmts:["Policy","LD","Speech"], act:13, t:1, seen:"2026" },
  { n:"Greenville Senior Academy", st:"SC", fmts:["Policy","LD","Congress","World Schools","Speech"], act:9, t:1, seen:"2026" },
  { n:"SD Academy", st:"SD", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:50, t:4, seen:"2026" },
  { n:"Hendersonville High School", st:"TN", fmts:["Policy","LD","Speech"], act:46, t:1, seen:"2026" },
  { n:"Sequoyah High School", st:"TN", fmts:["Policy","LD","Speech"], act:45, t:1, seen:"2026" },
  { n:"Collierville High School", st:"TN", act:36, t:1, seen:"2025" },
  { n:"Henry County High School", st:"TN", fmts:["Policy","LD","Speech"], act:20, t:1, seen:"2026" },
  { n:"Cookeville High School", st:"TN", fmts:["Policy","LD","Speech"], act:17, t:1, seen:"2026" },
  { n:"Brentwood Academy", st:"TN", fmts:["Policy","LD","Speech"], act:12, t:1, seen:"2026" },
  { n:"Rossview HS", st:"TN", fmts:["Policy","LD","Speech"], act:10, t:1, seen:"2026" },
  { n:"University School Of Nashville", st:"TN", fmts:["Policy","LD","Speech"], act:9, t:1, seen:"2026" },
  { n:"Strake Jesuit College Preparatory", st:"TX", fmts:["Policy","LD","PF","Congress","World Schools","Speech"], act:129, t:5, seen:"2026" },
  { n:"Greenhill School", st:"TX", fmts:["Policy","LD","PF","Congress","World Schools","Speech"], act:108, t:3, seen:"2026" },
  { n:"Grand Oaks High School", st:"TX", fmts:["Policy","LD","Congress","World Schools","Speech"], act:85, t:3, seen:"2026" },
  { n:"Liberal Arts and Science Academy", st:"TX", fmts:["Policy","LD","Congress","World Schools","Speech"], act:73, t:4, seen:"2027" },
  { n:"Seven Lakes High School", st:"TX", fmts:["Policy","LD","Congress","World Schools","Speech"], act:53, t:3, seen:"2026" },
  { n:"Lindale High School", st:"TX", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:42, t:3, seen:"2026" },
  { n:"Westlake (CA) High School", st:"TX", fmts:["Congress","World Schools","Big Questions","Speech"], act:39, t:3, seen:"2026" },
  { n:"The Awty International School", st:"TX", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:35, t:3, seen:"2026" },
  { n:"Jersey Village High School", st:"TX", fmts:["Policy","LD","Speech"], act:31, t:1, seen:"2026" },
  { n:"Alief Elsik High School", st:"TX", fmts:["Policy","LD","Speech"], act:31, t:1, seen:"2026" },
  { n:"Highland Park High School", st:"TX", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:31, t:2, seen:"2026" },
  { n:"The Woodlands College Park", st:"TX", act:29, t:1, seen:"2025" },
  { n:"Dripping Springs High School", st:"TX", fmts:["Policy","LD","Congress","World Schools","Speech"], act:28, t:2, seen:"2026" },
  { n:"Colleyville Heritage High School", st:"TX", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:28, t:3, seen:"2026" },
  { n:"Mahesh Independent", st:"TX", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:28, t:4, seen:"2026" },
  { n:"Prosper High School", st:"TX", act:26, t:1, seen:"2025" },
  { n:"Hendrickson High School", st:"TX", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:24, t:2, seen:"2026" },
  { n:"Cypress Springs High School", st:"TX", fmts:["Policy","LD","Speech"], act:21, t:1, seen:"2026" },
  { n:"Lake Travis High School", st:"TX", fmts:["Policy","LD","Speech"], act:18, t:1, seen:"2026" },
  { n:"Lampasas High School", st:"TX", act:14, t:1, seen:"2025" },
  { n:"Alief Early College High School", st:"TX", fmts:["Policy","LD","Speech"], act:13, t:1, seen:"2026" },
  { n:"Ysleta High School", st:"TX", fmts:["Policy","LD","Speech"], act:12, t:1, seen:"2026" },
  { n:"Stratford High School", st:"TX", fmts:["Policy","LD","Congress","World Schools","Speech"], act:12, t:2, seen:"2026" },
  { n:"Walnut Grove High School", st:"TX", act:11, t:1, seen:"2025" },
  { n:"Harlingen HS South", st:"TX", fmts:["Policy","LD","Speech"], act:10, t:1, seen:"2026" },
  { n:"Spring Woods High School", st:"TX", fmts:["Policy","LD","Speech"], act:9, t:1, seen:"2026" },
  { n:"Hanks High School", st:"TX", fmts:["Policy","LD","Speech"], act:8, t:1, seen:"2026" },
  { n:"SLC Independent", st:"UT", fmts:["Policy","LD","Speech"], act:7, t:1, seen:"2026" },
  { n:"The Potomac School", st:"VA", fmts:["Policy","LD","PF","Congress","World Schools","Speech"], act:89, t:3, seen:"2026" },
  { n:"Nysmith School", st:"VA", fmts:["Policy","LD","Congress","World Schools","Speech"], act:26, t:3, seen:"2026" },
  { n:"Floyd County High School", st:"VA", fmts:["Policy","LD","Congress","World Schools","Speech"], act:16, t:2, seen:"2026" },
  { n:"Dartmouth College", st:"VT", act:18, t:2, seen:"2026" },
  { n:"Interlake High School", st:"WA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:131, t:3, seen:"2026" },
  { n:"Bellevue Youth Debate", st:"WA", fmts:["Congress","World Schools","Big Questions","Speech"], act:72, t:3, seen:"2026" },
  { n:"The Overlake School", st:"WA", fmts:["Congress","World Schools","Big Questions","Speech"], act:40, t:1, seen:"2026" },
  { n:"Nexus Independent", st:"WA", fmts:["Congress","World Schools","Big Questions","Speech"], act:27, t:1, seen:"2026" },
  { n:"Innovation High School", st:"WA", fmts:["Policy","LD","Congress","World Schools","Speech"], act:20, t:2, seen:"2026" },
  { n:"Puyallup High School", st:"WA", act:19, t:1, seen:"2026" },
  { n:"Whitman College", st:"WA", act:18, t:2, seen:"2026" },
  { n:"Seattle Academy", st:"WA", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:16, t:2, seen:"2026" },
  { n:"Eastlake High School", st:"WA", fmts:["Policy","LD","Speech"], act:11, t:1, seen:"2026" },
  { n:"Neenah High School", st:"WI", fmts:["Policy","LD","Speech"], act:12, t:1, seen:"2026" },
  { n:"Fort Atkinson High School", st:"WI", fmts:["Policy","LD","PF","Congress","World Schools"], act:11, t:1, seen:"2025" },
  { n:"Potomac Debate Academy", st:"WV", fmts:["Policy","LD","Congress","World Schools","Big Questions","Speech"], act:136, t:3, seen:"2026" },
  { n:"Wheeling Park High School", st:"WV", fmts:["Policy","LD","Congress","World Schools","Speech"], act:17, t:1, seen:"2026" },
  { n:"Brooke High School", st:"WV", fmts:["Policy","LD","Speech"], act:7, t:1, seen:"2026" },
  { n:"Potomac Academy", st:"WV" },
  { n:"Natrona County High School", st:"WY", fmts:["Policy","LD","Speech"], act:14, t:1, seen:"2026" },
];

export const STATE_NAMES = {
  "AL": "Alabama",
  "AR": "Arkansas",
  "AZ": "Arizona",
  "CA": "California",
  "CO": "Colorado",
  "CT": "Connecticut",
  "DC": "District of Columbia",
  "FL": "Florida",
  "GA": "Georgia",
  "IA": "Iowa",
  "ID": "Idaho",
  "IL": "Illinois",
  "IN": "Indiana",
  "KY": "Kentucky",
  "LA": "Louisiana",
  "MA": "Massachusetts",
  "MD": "Maryland",
  "ME": "Maine",
  "MI": "Michigan",
  "MN": "Minnesota",
  "MO": "Missouri",
  "MS": "Mississippi",
  "NC": "North Carolina",
  "NE": "Nebraska",
  "NH": "New Hampshire",
  "NJ": "New Jersey",
  "NM": "New Mexico",
  "NV": "Nevada",
  "NY": "New York",
  "OH": "Ohio",
  "OK": "Oklahoma",
  "OR": "Oregon",
  "PA": "Pennsylvania",
  "RI": "Rhode Island",
  "SC": "South Carolina",
  "SD": "South Dakota",
  "TN": "Tennessee",
  "TX": "Texas",
  "UT": "Utah",
  "VA": "Virginia",
  "VT": "Vermont",
  "WA": "Washington",
  "WI": "Wisconsin",
  "WV": "West Virginia",
  "WY": "Wyoming"
};
