// ── Tournament engine ──────────────────────────────────────────────
//
// Pure functions. No Firestore, no network, no clock, no Math.random
// unless a seed is handed in. Everything here is deterministic given
// its inputs, which is the whole point: a draw that can't be
// reproduced can't be defended when a coach asks why their team hit
// the same opponent twice, and a tab that can't be recomputed from
// its own results is a tab nobody should trust.
//
// The vocabulary is the one debaters already use:
//   entry     a team (or a solo debater) registered in the tournament
//   prelim    a preliminary round; everyone debates
//   bracket   the set of entries on the same win count
//   pull-up   an entry moved out of its bracket to make the numbers work
//   bye       an unpaired entry; scored as a win, no speaks earned
//   break     the cut from prelims into elimination rounds
//   elim      a single-elimination round; loser goes home
//
// Callers own persistence and side effects. `tournament-admin.mjs`
// reads entries out of Firestore, calls into here, and writes the
// pairings back.

// ── Determinism helpers ────────────────────────────────────────────

// mulberry32. Small, fast, good enough for pairing, and identical
// across every runtime we care about. The seed is stored on the round
// so the draw can be regenerated byte-for-byte during a dispute.
export function rng(seed) {
  let a = (seed >>> 0) || 1;
  return function next() {
    a |= 0; a = (a + 0x6D2B79F5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// Seed from a string (the tournament id plus round number), so a
// caller that forgets to pass a numeric seed still gets a stable one.
export function seedFrom(str) {
  let h = 2166136261;
  const s = String(str || '');
  for (let i = 0; i < s.length; i += 1) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

export function shuffle(arr, next) {
  const out = arr.slice();
  for (let i = out.length - 1; i > 0; i -= 1) {
    const j = Math.floor(next() * (i + 1));
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}

// ── Entry shape ────────────────────────────────────────────────────
// Everything the engine needs about one team. Callers pass whatever
// else they like; these are the fields read here.
//
//   entryId   string, stable
//   name      string, display
//   wins      number of prelim ballots won so far
//   speaks    cumulative speaker points (the standard tiebreak)
//   sideCount { gov: n, opp: n }
//   opponents [entryId] every entry already faced
//   byes      number of byes already received
//   status    'registered' | 'checked_in' | 'withdrawn' | 'dropped'

const ACTIVE = new Set(['registered', 'checked_in']);

export function activeEntries(entries) {
  return (entries || []).filter((e) => ACTIVE.has(String(e.status || 'registered')));
}

function norm(e) {
  return {
    ...e,
    wins: Number(e.wins || 0),
    speaks: Number(e.speaks || 0),
    byes: Number(e.byes || 0),
    sideCount: { gov: Number(e.sideCount?.gov || 0), opp: Number(e.sideCount?.opp || 0) },
    opponents: Array.isArray(e.opponents) ? e.opponents : [],
  };
}

// ── Standings ──────────────────────────────────────────────────────
//
// Wins first, then speaker points. Debate tabs usually add more
// tiebreaks than this (opponent strength, ballot count, judge
// variance); those are only meaningful once there is enough data to
// separate teams, and adding them here without a real tournament to
// calibrate against would be inventing precision. Ties are broken
// LAST by entryId so the order is stable across recomputes rather
// than dependent on document read order.
export function standings(entries) {
  return activeEntries(entries).map(norm).sort((a, b) => {
    if (b.wins !== a.wins) return b.wins - a.wins;
    if (b.speaks !== a.speaks) return b.speaks - a.speaks;
    return String(a.entryId).localeCompare(String(b.entryId));
  });
}

// ── Side balance ───────────────────────────────────────────────────
//
// Whoever has been Gov less takes Gov. Even on the count, the higher
// seed takes Gov, which at least makes the assignment explainable.
function assignSides(a, b, next) {
  const aDebt = a.sideCount.gov - a.sideCount.opp;
  const bDebt = b.sideCount.gov - b.sideCount.opp;
  if (aDebt < bDebt) return { gov: a, opp: b };
  if (bDebt < aDebt) return { gov: b, opp: a };
  return next() < 0.5 ? { gov: a, opp: b } : { gov: b, opp: a };
}

// ── Matching ───────────────────────────────────────────────────────
//
// The draw is one GLOBAL rematch-free matching over the rank-ordered
// field, not a series of independent per-bracket matchings.
//
// That distinction is the difference between a clean draw and a
// broken one, and it only shows up late in a tournament. Pairing each
// win-bracket in isolation looks right and fails predictably: two
// teams end a round on the same record precisely BECAUSE they just
// debated each other, so by round 4 or 5 the small brackets are full
// of pairs who have already met, and a bracket that cannot pair
// itself has no move left except to run the rematch. Measured on the
// per-bracket version: 4 rematches in a 12-team field over 5 rounds,
// 2 in a 16-team field, with side skew reaching 3.
//
// Matching globally, an unpairable bracket simply reaches one place
// further down the standings for a partner. Because the search is
// exhaustive it finds a rematch-free draw whenever one exists at all,
// and because candidates are tried in cost order the pull is always
// the smallest one available.
//
// Cost order per candidate, cheapest first:
//   1. bracket distance   how many wins apart (0 = a true power pair)
//   2. side pressure      |debt(a) + debt(b)|, so a team owed Gov is
//                         matched with a team owed Opp and both come
//                         back to even
//   3. rank proximity     the nearest remaining opponent
//
// Side pressure sits INSIDE the matching rather than being applied
// after it. Assigning sides to an already-fixed pairing can only
// choose the lesser of two bad options when both teams owe the same
// side; choosing the partner is what actually keeps the count even.
function sideDebt(e) {
  return e.sideCount.gov - e.sideCount.opp;
}

// Exhaustive search is exponential in the worst case. Real fields
// never approach it (the first candidate is almost always accepted),
// but a pathological opponent history must not hang a director's
// browser mid-tournament, so the search is bounded and degrades to a
// relaxed draw instead of running forever.
const SEARCH_BUDGET = 50000;

function matchGlobally(list) {
  if (list.length % 2 !== 0) return { pairs: null, exhausted: false };
  const n = list.length;
  const used = new Array(n).fill(false);
  const pairs = [];
  let steps = 0;
  let exhausted = false;

  const met = list.map((a) => new Set(a.opponents));

  function candidates(i) {
    const out = [];
    for (let j = i + 1; j < n; j += 1) {
      if (used[j]) continue;
      if (met[i].has(list[j].entryId) || met[j].has(list[i].entryId)) continue;
      out.push({
        j,
        bracket: Math.abs(list[i].wins - list[j].wins),
        side: Math.abs(sideDebt(list[i]) + sideDebt(list[j])),
      });
    }
    out.sort((x, y) => (x.bracket - y.bracket) || (x.side - y.side) || (x.j - y.j));
    return out;
  }

  function firstFree() {
    for (let i = 0; i < n; i += 1) if (!used[i]) return i;
    return -1;
  }

  function solve() {
    if (steps > SEARCH_BUDGET) { exhausted = true; return false; }
    const i = firstFree();
    if (i === -1) return true;
    used[i] = true;
    const cands = candidates(i);
    for (let c = 0; c < cands.length; c += 1) {
      steps += 1;
      if (steps > SEARCH_BUDGET) { exhausted = true; break; }
      const { j } = cands[c];
      used[j] = true;
      pairs.push([list[i], list[j]]);
      if (solve()) return true;
      pairs.pop();
      used[j] = false;
    }
    used[i] = false;
    return false;
  }

  const ok = solve();
  return { pairs: ok ? pairs : null, exhausted };
}

// Relaxed fallback, used only when no rematch-free draw exists at all
// (a small field that has run out of fresh opponents) or when the
// search budget is spent. Still power-paired and still side-aware;
// the only constraint dropped is the rematch ban.
function lexLess(a, b) {
  for (let i = 0; i < a.length; i += 1) {
    if (a[i] !== b[i]) return a[i] < b[i];
  }
  return false;
}

function matchRelaxed(list) {
  const remaining = list.slice();
  const pairs = [];
  while (remaining.length >= 2) {
    const a = remaining.shift();
    let bestIdx = 0;
    let bestKey = null;
    for (let j = 0; j < remaining.length; j += 1) {
      const b = remaining[j];
      const key = [
        a.opponents.includes(b.entryId) ? 1 : 0,
        Math.abs(a.wins - b.wins),
        Math.abs(sideDebt(a) + sideDebt(b)),
        j,
      ];
      if (bestKey === null || lexLess(key, bestKey)) { bestKey = key; bestIdx = j; }
    }
    pairs.push([a, remaining.splice(bestIdx, 1)[0]]);
  }
  return pairs;
}

// ── Side repair ────────────────────────────────────────────────────
//
// The matching above picks partners greedily in cost order, which is
// near-optimal for sides but not optimal: it can still leave a pair
// where both teams owe the same side, and that pair is where a team
// picks up a third or fourth Gov. Measured before this pass, a 32-team
// field could hand one team four Govs in five rounds. That is the
// version of this a coach emails about.
//
// So the draw gets a repair pass: repeatedly look for two pairings
// that would both improve by trading partners. Swaps that would
// create a rematch are rejected outright, and bracket distance is
// weighted an order of magnitude above side cost so a repair can
// never quietly un-power-pair the round to flatten a side count.
// Bounded and strictly improving, so it always terminates.
function pairCost(a, b) {
  return 10 * Math.abs(a.wins - b.wins) + Math.abs(sideDebt(a) + sideDebt(b));
}

function metBefore(a, b) {
  return a.opponents.includes(b.entryId) || b.opponents.includes(a.entryId);
}

function repairSides(pairs) {
  const MAX_SWEEPS = 12;
  for (let sweep = 0; sweep < MAX_SWEEPS; sweep += 1) {
    let improved = false;
    for (let i = 0; i < pairs.length; i += 1) {
      for (let j = i + 1; j < pairs.length; j += 1) {
        const [a, b] = pairs[i];
        const [c, d] = pairs[j];
        const before = pairCost(a, b) + pairCost(c, d);
        const options = [];
        if (!metBefore(a, c) && !metBefore(b, d)) {
          options.push({ cost: pairCost(a, c) + pairCost(b, d), left: [a, c], right: [b, d] });
        }
        if (!metBefore(a, d) && !metBefore(b, c)) {
          options.push({ cost: pairCost(a, d) + pairCost(b, c), left: [a, d], right: [b, c] });
        }
        options.sort((x, y) => x.cost - y.cost);
        if (options.length && options[0].cost < before) {
          pairs[i] = options[0].left;
          pairs[j] = options[0].right;
          improved = true;
        }
      }
    }
    if (!improved) break;
  }
  return pairs;
}

// ── Bye selection ──────────────────────────────────────────────────
//
// An odd field means someone sits out. The bye goes to the entry with
// the fewest byes so far, and among those the lowest-ranked, because
// a free win hurts least at the bottom of the tab. Round 1 has no
// standings, so it falls out of the shuffle instead.
function pickBye(ranked) {
  let choice = null;
  for (let i = ranked.length - 1; i >= 0; i -= 1) {
    const e = ranked[i];
    if (!choice || e.byes < choice.byes) choice = e;
    if (choice.byes === 0) break;
  }
  return choice;
}

// ── Prelim pairing ─────────────────────────────────────────────────
//
// roundNo 1 is a random draw. Every later round is power-paired:
// entries are grouped by win count, each bracket is paired internally
// avoiding rematches, and an odd bracket sends its lowest-ranked
// entry down to join the next bracket (the pull-up).
//
// Returns { pairings: [{gov, opp, ...}], bye, seed, brackets }.
// Nothing is written; the caller persists.
export function pairPrelimRound(entries, roundNo, opts = {}) {
  const seed = opts.seed != null ? opts.seed : seedFrom((opts.tid || 't') + ':r' + roundNo);
  const next = rng(seed);
  const active = activeEntries(entries).map(norm);

  if (active.length < 2) {
    return { pairings: [], bye: null, seed, brackets: [], error: 'Need at least two entries to pair a round.' };
  }

  const ranked = Number(roundNo) <= 1
    ? shuffle(active, next)
    : standings(active);

  let pool = ranked;
  let bye = null;
  if (pool.length % 2 === 1) {
    bye = Number(roundNo) <= 1 ? pool[pool.length - 1] : pickBye(pool);
    pool = pool.filter((e) => e.entryId !== bye.entryId);
  }

  // One global matching over the whole rank-ordered pool. Round 1's
  // pool is already shuffled and every entry is on 0 wins, so the
  // bracket term is uniformly zero and this reduces to a random draw.
  const { pairs: clean, exhausted } = matchGlobally(pool);
  const pairs = repairSides(clean || matchRelaxed(pool));
  const rematchFallback = !clean;

  // What the draw actually cost, for the director and for the round
  // record. pullUps counts pairings across win brackets; rematches is
  // the number that survived the fallback (0 on a clean draw).
  const pullUps = pairs.filter(([a, b]) => a.wins !== b.wins).length;
  const rematches = pairs.filter(([a, b]) => a.opponents.includes(b.entryId)).length;

  const pairings = pairs.map(([a, b], i) => {
    const { gov, opp } = assignSides(a, b, next);
    return {
      pairingId: 'r' + roundNo + '-' + (i + 1),
      roundNo: Number(roundNo),
      kind: 'prelim',
      govEntry: gov.entryId,
      govName: gov.name || 'Team',
      oppEntry: opp.entryId,
      oppName: opp.name || 'Team',
      room: '',
      status: 'pending',
      winner: '',
    };
  });

  return {
    pairings,
    bye: bye ? { entryId: bye.entryId, name: bye.name || 'Team' } : null,
    seed,
    // Draw quality, surfaced rather than buried. A director who sees
    // rematches on the sheet deserves to know the tab knew too.
    pullUps,
    rematches,
    rematchFallback,
    searchExhausted: exhausted,
  };
}

// ── Drop-in pairing ────────────────────────────────────────────────
//
// pairPrelimRound above assumes a SYNCHRONOUS tournament: everybody
// plays round 1, the director pairs round 2, and so on. /tournaments
// promises the opposite, and has since the all-day format was decided:
// doors open, you turn up whenever, you get paired, you play as many
// rounds as you like. On a small base that is the right call, because a
// fixed start time needs everyone free at the same hour while an
// all-day pool only needs two people awake at once.
//
// Nothing here re-implements the draw. The matcher, the side repair and
// the side assignment are the same functions the synchronous path uses,
// so drop-in inherits the rematch ban, the power pairing and the side
// balance rather than growing a second-rate copy of them. What changes
// is only WHO is in the pool and what happens to an odd one out.
//
// Two rules that are specific to drop-in and easy to get wrong:
//
// 1. THERE ARE NO BYES. In a synchronous round a bye is a free win
//    handed to whoever the field could not seat, and byePatch awards
//    one. In drop-in an unpaired entrant has not missed a round, they
//    are simply next in line, so they WAIT. Awarding a bye here would
//    make arriving at an odd moment worth a free win, which is the
//    cheapest possible way to farm a $500 prize.
//
// 2. THE LONGEST WAITER GETS PRIORITY. The pool is ordered by
//    standings so the matcher still power-pairs, but when the pool is
//    odd the person who sits out is the one who just arrived, never the
//    one who has been waiting twenty minutes. Without that rule a
//    steady trickle of arrivals can starve someone indefinitely while
//    the board looks busy.
// 3. PATIENCE BEFORE A REPEAT. The pool available at any instant is
//    small even when the field is large, because most entrants are
//    mid-round. Seating the first legal pair the moment two people are
//    free therefore produces repeat matchups in a field with plenty of
//    fresh opponents: measured over a simulated 10-hour day at 25
//    minutes a round, an eager matcher gave a 40-entrant field 345
//    repeats across 411 rounds, which is not an opponent shortage, it
//    is the matcher choosing from whoever happens to be idle.
//
//    So when the only available draw needs a repeat, the engine waits
//    instead, up to DROPIN_REMATCH_PATIENCE_MS. A few more minutes in
//    the queue buys a much wider pool. Past that threshold a repeat is
//    seated, because a fresh opponent nobody can find is worth less
//    than a round you actually get to play.
const DROPIN_AVAILABLE_MS = 6 * 60 * 1000;   // a queue slot goes stale after 6 min of silence
const DROPIN_ODD_TRIES = 6;                  // how many sit-out candidates to try for a clean draw
//    PATIENCE MUST STAY BELOW THE STALENESS WINDOW. Set it above and the
//    two rules deadlock: an entrant holding out for a fresh opponent
//    ages out of the pool before the gate ever releases them, so the
//    queue empties itself and nobody plays. Measured with patience at 8
//    minutes against a 6-minute window, a 6-entrant day ran 3 rounds
//    instead of 69. The clamp below makes that unrepresentable rather
//    than relying on whoever edits these two numbers next to notice.
const DROPIN_REMATCH_PATIENCE_MS = 4 * 60 * 1000;

function availableAtMs(e) {
  return Number(e.availableAt || 0);
}

/**
 * Everyone who could be paired right now: active, not already in a
 * round, and with a queue slot that has not gone stale. Stale slots are
 * excluded rather than deleted; the caller decides whether to clean up.
 */
export function availableForDropIn(entries, now, windowMs) {
  const w = Number(windowMs) || DROPIN_AVAILABLE_MS;
  const t = Number(now) || 0;
  return activeEntries(entries).map(norm).filter((e) => {
    if (e.inPairing) return false;
    const at = availableAtMs(e);
    return at > 0 && t - at <= w;
  });
}

/**
 * Pair whoever is available at this moment.
 *
 * @param entries  every entry doc; availability is derived, not passed
 * @param opts     { tid, seq, now, seed, windowMs }
 *                 `seq` is a monotonic counter the caller increments per
 *                 pairing attempt. It exists so the draw stays SEEDED
 *                 and reproducible: a coach asking why they hit the same
 *                 opponent twice can be answered from the record rather
 *                 than from memory, which is the same property the
 *                 synchronous draw has.
 * @returns { pairings, waiting, seed, rematches, pullUps, rematchFallback, searchExhausted }
 */
export function pairDropIn(entries, opts = {}) {
  const now = Number(opts.now) || 0;
  const seq = Number(opts.seq) || 0;
  const seed = opts.seed != null ? opts.seed : seedFrom((opts.tid || 't') + ':d' + seq);
  const next = rng(seed);

  const pool = availableForDropIn(entries, now, opts.windowMs);
  const waitingOf = (list) => list
    .slice()
    .sort((a, b) => availableAtMs(a) - availableAtMs(b))
    .map((e) => ({ entryId: e.entryId, name: e.name || 'Team', waitingMs: Math.max(0, now - availableAtMs(e)) }));

  if (pool.length < 2) {
    return { pairings: [], waiting: waitingOf(pool), seed, rematches: 0, pullUps: 0, rematchFallback: false, searchExhausted: false };
  }

  // Standings order is what makes the matcher power-pair: its third
  // cost term is index proximity, so a rank-ordered list means the
  // nearest acceptable opponent is the nearest in the standings.
  const ranked = standings(pool);

  let sitOut = [];
  let pairPool = ranked;
  let clean = null;
  let exhausted = false;

  if (ranked.length % 2 === 1) {
    // Try sitting out the most recently arrived first, then the next
    // most recent, and so on. Dropping purely by arrival order can
    // force a rematch that a different choice would have avoided, so
    // the first candidate that yields a rematch-free draw wins. Bounded
    // because the pool is small and a director's day is not.
    const byNewest = ranked.slice().sort((a, b) => availableAtMs(b) - availableAtMs(a));
    const tries = Math.min(DROPIN_ODD_TRIES, byNewest.length);
    for (let i = 0; i < tries; i += 1) {
      const cand = byNewest[i];
      const rest = ranked.filter((e) => e.entryId !== cand.entryId);
      const attempt = matchGlobally(rest);
      exhausted = exhausted || attempt.exhausted;
      if (attempt.pairs) { clean = attempt.pairs; pairPool = rest; sitOut = [cand]; break; }
    }
    if (!clean) {
      // No sit-out choice produces a clean draw. Fall back to the
      // newest waiting, which is the fair one, and let the relaxed
      // matcher run. Someone gets a rematch; nobody gets a free win.
      sitOut = [byNewest[0]];
      pairPool = ranked.filter((e) => e.entryId !== byNewest[0].entryId);
    }
  } else {
    const attempt = matchGlobally(ranked);
    exhausted = attempt.exhausted;
    clean = attempt.pairs;
  }

  // Patience: a repeat matchup is worth waiting a few minutes to avoid,
  // because the pool widens fast as rounds end. Everyone holds unless
  // somebody has already waited past the threshold, at which point a
  // repeat beats another twenty minutes in the queue.
  if (!clean) {
    const windowMs = Number(opts.windowMs) || DROPIN_AVAILABLE_MS;
    const wanted = Number.isFinite(Number(opts.rematchPatienceMs))
      ? Number(opts.rematchPatienceMs)
      : DROPIN_REMATCH_PATIENCE_MS;
    // Never hold longer than a queue slot survives. See the note above.
    const patience = Math.max(0, Math.min(wanted, windowMs - 60_000));
    const longestWait = pool.reduce((m, e) => Math.max(m, now - availableAtMs(e)), 0);
    if (longestWait < patience) {
      return {
        pairings: [],
        waiting: waitingOf(pool),
        seed,
        pullUps: 0,
        rematches: 0,
        rematchFallback: false,
        heldForFreshOpponent: true,
        searchExhausted: exhausted,
      };
    }
  }

  const pairs = repairSides(clean || matchRelaxed(pairPool));
  const rematchFallback = !clean;

  const pullUps = pairs.filter(([a, b]) => a.wins !== b.wins).length;
  const rematches = pairs.filter(([a, b]) => a.opponents.includes(b.entryId)).length;

  const pairings = pairs.map(([a, b], i) => {
    const { gov, opp } = assignSides(a, b, next);
    return {
      pairingId: 'd' + seq + '-' + (i + 1),
      // Drop-in play has no round number. Kept on the object at 0 so
      // every consumer that sorts or renders pairings keeps working;
      // `kind` is what distinguishes these from a paired round.
      roundNo: 0,
      kind: 'dropin',
      govEntry: gov.entryId,
      govName: gov.name || 'Team',
      oppEntry: opp.entryId,
      oppName: opp.name || 'Team',
      room: '',
      status: 'pending',
      winner: '',
      pairedAt: now,
    };
  });

  return {
    pairings,
    waiting: waitingOf(sitOut),
    seed,
    pullUps,
    rematches,
    rematchFallback,
    searchExhausted: exhausted,
  };
}

// ── Break ──────────────────────────────────────────────────────────
//
// The cut from prelims to elims. A bracket needs a power of two, so
// the requested size is rounded DOWN to one the field can actually
// fill. Rounding down rather than up is deliberate: a bracket padded
// with byes to reach the next power of two hands free wins to the top
// seeds, which is a worse outcome than a smaller, honest break.
export function breakField(entries, requestedSize) {
  const ranked = standings(entries);
  const want = Number(requestedSize || 0);
  let size = 2;
  while (size * 2 <= Math.min(want || ranked.length, ranked.length)) size *= 2;
  if (ranked.length < 2) return { breaking: [], size: 0, error: 'Not enough entries to break.' };
  const breaking = ranked.slice(0, size).map((e, i) => ({
    seed: i + 1,
    entryId: e.entryId,
    name: e.name || 'Team',
    wins: e.wins,
    speaks: e.speaks,
  }));
  // A tie ON the break line decides who goes home, so it gets
  // surfaced rather than silently resolved by sort order. The caller
  // shows it to the director; the standings tiebreak still produced a
  // definite order, so nothing is blocked.
  const last = ranked[size - 1];
  const first = ranked[size];
  const tieOnLine = !!(last && first && last.wins === first.wins && last.speaks === first.speaks);
  return { breaking, size, tieOnLine };
}

// Elim seeding: 1 plays the lowest seed, 2 plays the second lowest.
// Same shape every bracket in debate uses.
export function elimPairings(breaking, label, roundNo) {
  const n = breaking.length;
  const pairings = [];
  for (let i = 0; i < n / 2; i += 1) {
    const hi = breaking[i];
    const lo = breaking[n - 1 - i];
    pairings.push({
      pairingId: 'e' + roundNo + '-' + (i + 1),
      roundNo: Number(roundNo),
      kind: 'elim',
      label,
      govEntry: hi.entryId,
      govName: hi.name,
      govSeed: hi.seed,
      oppEntry: lo.entryId,
      oppName: lo.name,
      oppSeed: lo.seed,
      room: '',
      status: 'pending',
      winner: '',
    });
  }
  return pairings;
}

// The name a bracket of this size goes by. Anything above 16 is
// numbered rather than named, because "triple-octofinals" reads as a
// joke to everyone outside the few circuits that use it.
export function elimLabel(size) {
  if (size === 2) return 'Final';
  if (size === 4) return 'Semifinal';
  if (size === 8) return 'Quarterfinal';
  if (size === 16) return 'Octofinal';
  return 'Round of ' + size;
}

// Winners of an elim round, in seed order, ready to seed the next.
export function advanceElim(pairings) {
  const winners = [];
  pairings.forEach((p) => {
    if (p.winner === 'gov') winners.push({ entryId: p.govEntry, name: p.govName, seed: p.govSeed });
    else if (p.winner === 'opp') winners.push({ entryId: p.oppEntry, name: p.oppName, seed: p.oppSeed });
  });
  winners.sort((a, b) => Number(a.seed || 999) - Number(b.seed || 999));
  return winners.map((w, i) => ({ ...w, seed: w.seed || i + 1 }));
}

// ── Result application ─────────────────────────────────────────────
//
// Fold one reported result into an entry's record. Returns a patch,
// not a mutation, so the caller can decide how to persist it and so a
// double-report is the caller's problem to detect rather than a
// silent double-count here.
export function resultPatch(entry, { won, speaks, side, opponentEntryId }) {
  const e = norm(entry);
  return {
    wins: e.wins + (won ? 1 : 0),
    losses: Number(entry.losses || 0) + (won ? 0 : 1),
    speaks: e.speaks + Number(speaks || 0),
    sideCount: {
      gov: e.sideCount.gov + (side === 'gov' ? 1 : 0),
      opp: e.sideCount.opp + (side === 'opp' ? 1 : 0),
    },
    opponents: opponentEntryId ? e.opponents.concat([opponentEntryId]) : e.opponents,
  };
}

export function byePatch(entry) {
  const e = norm(entry);
  return {
    wins: e.wins + 1,
    byes: e.byes + 1,
    // A bye earns no speaker points. Awarding an average instead is
    // the other common convention, but it invents a score nobody
    // spoke for, and speaks are the tiebreak that decides the break.
    speaks: e.speaks,
  };
}
